- src/aap_eda/api/serializers/project.py
- src/aap_eda/api/views/project.py
- tests/integration/api/test_project.py
Now the request body for updating project accepts:
```
{
"url": "string",
"name": "string",
"description": "string",
"credential_id": 0
}
```
Solves: [AAP-13983](https://issues.redhat.com/browse/AAP-13983)
> [AAP-13983] Change patch project to accept credential id

- Taskfile.dist.yaml
- tools/docker/docker-compose-dev.yaml
Now that we have a docker-compose for macs we can add the latest updates from the stage env to the docker-compose-dev. 
Includes:
- Add podman service for activations to not depend on local podman anymore as we do in stage env. 
- Add the envvar for EDA_NUM_WORKERS and update the default value to match the stage env
- Remove postgres extra stuff not present in the stage or the operator env to use the default ones. 
- Add envvars for AWX integration. 
- Add UI pod
- Update pod names to the same values in stage (ui expects a hostname called "eda-api")
> Update docker compose dev: equate with stage env

- src/aap_eda/services/project/git.py
- tests/unit/test_git.py
Includes
- Prevent to leak git password in logs and exception when git fails. 
- Specify in the exception when it is an authentication error. 
Internal ref: https://issues.redhat.com/browse/AAP-12767
> fix: hide password when cloning projects

- src/aap_eda/api/serializers/__init__.py
- src/aap_eda/api/serializers/project.py
- src/aap_eda/api/views/project.py
- tests/integration/api/test_project.py
In this PR:
1. allow to update project with credential_id is 0 or None (clear credential from project);
2. raise 400 bad request if credential_id is invalid (the credential not found);
3. update fields only accept `name, description and credential_id`, 'url` cannot be updated.
Solves: [AAP-14441](https://issues.redhat.com/browse/AAP-14441)
> [AAP-14441] Add more details when updating projects

- src/aap_eda/tasks/ruleset.py
After the implementation of the scheduler, activations are no longer restart automatically. It throws the error:
```
eda-default-worker_1     | 2023-07-31 11:51:46,784 INFO     default: aap_eda.tasks.ruleset.activate_rulesets(args=(True, 9, 'podman', 'ws://eda-api:8000', 'no')) (7553dead-9b13-4d62-ab37-4883eafbb4fc)
eda-default-worker_1     | 2023-07-31 11:51:46,792 ERROR    [Job 7553dead-9b13-4d62-ab37-4883eafbb4fc]: exception raised while executing (aap_eda.tasks.ruleset.activate_rulesets)
eda-default-worker_1     | Traceback (most recent call last):
eda-default-worker_1     |   File "/app/venv/lib64/python3.9/site-packages/rq/worker.py", line 1359, in perform_job
eda-default-worker_1     |     rv = job.perform()
eda-default-worker_1     |   File …
```
> Fix enqueue_restart_task for activations restart

- src/aap_eda/core/management/commands/scheduler.py
When I took https://github.com/ansible/eda-server/pull/321 I merged two functions thinking they were the same code as it was suggested, but I didn't notice that it calls different methods of the scheduler which accepts a different set of arguments, so even if the code is pretty similar IMO the original approach of keeping them in different functions is the right one.
> Fix rqscheduler initialization

- src/aap_eda/api/serializers/activation.py
- src/aap_eda/api/views/activation.py
- tests/integration/api/test_activation.py
- Add missing last restarted date field on Activations Read Endpoint: `http://localhost:8000/api/eda/v1/activations/<activation_id>/`
> [AAP-13795] Add Activation missing last restarted field

- tools/docker/docker-compose-dev.yaml
- tools/docker/docker-compose-stage.yaml
Every time the docker-compose is started all the images must be downloaded again. Adding an extra time and traffic. This is unnecessary an inefficient. This PR persist the podman data as we do with the database.
> Persist podman data for docker-compose

- src/aap_eda/core/tasking/__init__.py
- src/aap_eda/tasks/ruleset.py
Minor fixes around tasking:
- Wrong default value and type hint in the Queue subclass
- Remove unused param in the Activation Worker constructor
- Use datetime.utcnow as it is indicated in the [RQ scheduler documentation](https://github.com/rq/rq-scheduler#scheduling-a-job)
> Fix tasking subclasses and use datetime.utcnow

- src/aap_eda/api/serializers/activation.py
- src/aap_eda/api/views/activation.py
- tests/integration/api/test_activation.py
- Fix 500 error thrown on Activation creation when non-existent rulebook ID is passed
- Improve unit test for create activation unprocessible entity
- Add a check for decision environment existence on Activation creation
Solves: [AAP-11738](https://issues.redhat.com/browse/AAP-11738)
> [AAP-11738] Fix 500 error on Activation creation

- src/aap_eda/core/tasking/__init__.py
Restore required param deleted by mistake in https://github.com/ansible/eda-server/pull/335
> Restore queue param in initializer of activation worker

- tools/deploy/eda-default-worker/deployment.yaml
Because deactivation is moved to default worker to process, its envs need to set DEPLOYMENT_TYPE=k8s. Otherwise deactivation task will run as local type and fail.
> Add deployment_type into default worker's envs for K8S

- tools/docker/docker-compose-mac.yml
host mode does not allow to publish container ports to host. Default network mode bridge better suits for our needs.
Fixes AAP-15014: [API] podman activation does not expose ports properly
> [AAP-15014] Do not set network_mode to host

- tools/docker/docker-compose-dev.yaml
- tools/docker/docker-compose-mac.yml
- tools/docker/docker-compose-stage.yaml
Based on PR https://github.com/ansible/ansible-ui/pull/766 We need to add 2 environment variables to the eda-ui container
* EDA_PROTOCOL
* EDA_HOST
Without this change in we were getting an error when starting the eda-ui container
```
eda-ui_1                 | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
eda-ui_1                 | /docker-entrypoint.sh: Configuration complete; ready for start up
eda-ui_1                 | 2023/08/15 18:51:28 [emerg] 1#1: unknown "eda_protocol" variable
eda-ui_1                 | nginx: [emerg] unknown "eda_protocol" variable
docker_eda-ui_1 exited with code 1
```
> chore: fix docker-compose for changes in eda-ui image

- src/aap_eda/wsapi/consumers.py
- tests/integration/wsapi/test_consumer.py
When the same fact/event matches multiple rules we were not storing the events for the rules other than the first one. This PR ensures that the events are stored for every rule that matches.
https://issues.redhat.com/browse/AAP-15158
> fix: handle multiple rule matching to the same fact/event

- src/aap_eda/api/views/activation.py
- src/aap_eda/services/ruleset/activate_rulesets.py
- src/aap_eda/services/ruleset/activation_db_logger.py
- src/aap_eda/services/ruleset/activation_kubernetes.py
- src/aap_eda/services/ruleset/activation_podman.py
- src/aap_eda/services/ruleset/exceptions.py
- src/aap_eda/tasks/ruleset.py
- src/aap_eda/wsapi/consumers.py
- tests/integration/api/test_activation.py
This PR refactored the activation deletion logic as follows:
1. marks the activation's status to `deleting` in api worker, so UI can display it with correct status;
2. disable the activation to cleanup the jobs in queue and the running containers if necessary in default worker;
3. delete the activation from DB in default worker;
Solves [AAP-13416](https://issues.redhat.com/browse/AAP-13416)
> [AAP-13416] Move activation deletion to default worker

- tools/deploy/eda-activation-worker/deployment.yaml
The activation worker deployment file was missing the EDA_DEPLOYMENT_TYPE=k8s
And it would try running the podman deployment type and fail.
> chore: missing EDA_DEPLOYMENT_TYPE in the deployment file

- src/aap_eda/services/ruleset/activate_rulesets.py
- src/aap_eda/services/ruleset/activation_kubernetes.py
This PR reformats the log message when a failed activation restarts.
Solves: [AAP-13345](https://issues.redhat.com/browse/AAP-13345)
> [AAP-13345] Fix log message when a failed activation restarts

- src/aap_eda/api/serializers/activation.py
- src/aap_eda/api/views/activation.py
- tests/integration/api/test_activation.py
* Removes project_id from POST Activations request payload
* Populates the project field using the rulebook field value
> Remove project_id from POST Activations

- src/aap_eda/tasks/ruleset.py
Little hotfix for the changes introduced by https://github.com/ansible/eda-server/pull/338
Jira: https://issues.redhat.com/browse/AAP-15719
> fix: missing arg to _perform_deactivate call at activation restart - AAP-15719

- src/aap_eda/api/views/activation.py
Little fix for https://github.com/ansible/eda-server/pull/327
`restarted_at` field should not have value if the activation has not been restarted.
> fix: fix logic of restarted_at field for activations

- src/aap_eda/wsapi/consumers.py
The DatabaseError raised in parsing heartbeat message may be the reason of GH e2e tests failure.
Solves: [AAP-15867](https://issues.redhat.com/browse/AAP-15867)
> [AAP-15867] Except DatabaseError in parsing heartbeat message

- src/aap_eda/services/ruleset/activate_rulesets.py
- tests/integration/services/test_ruleset_activate.py
Fixes AAP-16014: Activation not marked failed if exception is raised
This bug was introduced by recent bug fixing work on deactivation (#355), thus is needed before our next release.
> [AAP-16014] Fail activation on exception

- tools/deploy/postgres/deployment.yaml
- tools/deploy/redis/deployment.yaml
- tools/docker/docker-compose-dev.yaml
- tools/docker/docker-compose-mac.yml
- tools/docker/docker-compose-stage.yaml
All our development environments use a different image of postgres and redis than our operator. In the case of the redis we are using a different version as well. We must use the images that use the operator from the sclorg project, based in centos which is an environment closer to downstream.
Jira: https://issues.redhat.com/browse/AAP-15659
> Align postgres and redis images with eda-operator - AAP-15659

- src/aap_eda/api/serializers/activation.py
* Add `allow_null=True` to `activation.rulebook` field to reflect it on the openapi spec, although it is already nullable the openapi doesn't pick it up unless explicitly specified.
> chore: update activation.rulebook field openapi spec

- tools/deploy/postgres/deployment.yaml
- tools/docker/docker-compose-dev.yaml
- tools/docker/docker-compose-mac.yml
- tools/docker/docker-compose-stage.yaml
c8s images doesn't have support for ARM, moving it to c9s that has it. 
Also includes a fix related with the startup order. If the DB is clean, the workers might run before complete the migrations and fail.
> chore: upgrade pg image and improve startup order

- tests/unit/test_permissions.py
A target can only be considered valid within the context.
> (chore) Use context manager targets only in context.

- src/aap_eda/services/exceptions.py
- src/aap_eda/services/ruleset/activation_podman.py
Due to a bug in podman we are not handling exception when the image pull fails, raising a misleading error message after try to run the activation. 
Jira: https://issues.redhat.com/browse/AAP-16189
> fix: handle errors at pulling images for podman - AAP-16189

- tools/deploy/eda-ui/deployment.yaml
- tools/docker/docker-compose-dev.yaml
- tools/docker/docker-compose-mac.yml
- tools/docker/docker-compose-stage.yaml
The image built as part of the Ansible UI will be moving back to the EDA_SERVER env variable instead of EDA_PROTOCOL and EDA_HOST.
This should make it so that the docker-compose supports both until EDA_PROTOCOL and EDA_HOST can be removed in the future.
> Update EDA UI env variables to support EDA_SERVER

- tools/deploy/redis/deployment.yaml
The `quay.io/sclorg/redis-6-c9s:latest` redis image broke when deploying in k8s env. Changed it to use v6: `docker.io/library/redis:6`
> Changed to use v6 Redis image for k8s deployment

- .github/workflows/ci.yaml
- docs/development.md
- poetry.lock
- pyproject.toml
- src/aap_eda/core/tasking/__init__.py
- src/aap_eda/settings/default.py
- src/aap_eda/tasks/project.py
- tests/integration/conftest.py
- tests/integration/core/test_tasking.py
- tests/integration/tasks/test_projects.py
Problem: if the broker is restarted we might have stuck projects pending to be synced/imported without a job in the queue. 
Includes:
- A new task to monitor projects in a similar way as monitor_activations does. It recreates the jobs if don't exist and their respective tests
- A new pytest plugin to use redis in a similar way as pytest-django does to use a real redis for integration tests. WARNING: Now redis is required to run the tests. This will be also necessary in later refactors of the integration tests to provide more coverage on tests that involves RQ tasks
- Add a redis instance and updates the postgres image in the CI pipeline following up: https://github.com/ansible/eda-server/pull/405 and https://github.com/ansible/eda-server/pull/384
- Tests for unique_enqueue plus docstring …
> fix: watch for projects stuck in pending state

- poetry.lock
- pyproject.toml
Fix for https://github.com/ansible/eda-server/pull/396
pytest-redis was added as app dependency instead of test dependency.
> chore(deps) fix dep, moves pytest-redis to test group

- src/aap_eda/services/ruleset/activation_podman.py
Even `dict` is acceptable in `update_fields` (https://docs.djangoproject.com/en/4.2/ref/models/instances/#ref-models-update-fields), we'd better to change it to list.
> The update_fields argument can be any iterable containing strings. An empty update_fields iterable will skip the save. A value of None will perform an update on all fields.
> Changed update_fields of save to use list

- src/aap_eda/wsapi/consumers.py
- tests/integration/wsapi/test_consumer.py
When the server side receives a websocket messages each message is handled by a separate asyncio task. In the task the first thing we do is send a "Hello" message to the ansible-rulebook. If ansible rulebook terminates before this Hello message gets to its the asyncio task aborts and doesn't write any messages into the DB. This leads to messages getting lost.
With this fix now we send the "Hello" message only after we have written the data to the DB.
https://issues.redhat.com/browse/AAP-16264
> fix: send the Hello message after the DB is updated

- src/aap_eda/core/enums.py
- src/aap_eda/core/exceptions.py
- src/aap_eda/core/models/activation.py
- tests/integration/api/test_activation.py
- tests/integration/api/test_activation_instance.py
- tests/integration/core/test_activation.py
- tests/integration/core/test_activation_instance.py
- tests/integration/tasks/test_ruleset.py
This is the followup of https://github.com/ansible/eda-server/pull/416: update the `status_message` of activations/instances with default values when their status is changed.
> [AAP-16339] Add default status_message to activations and instances when updating their status

- src/aap_eda/api/views/decision_environment.py
Test suites is failing due to wrong defined response type for DE. This PR will set the correctly formatted response type for Delete DE endpoint.
> chore: Fix Delete Decision Environment response type

- src/aap_eda/services/project/git.py
Follow up: https://github.com/ansible/eda-server/pull/322 which handle wrong credentials. 
Now we handle as well the repo requires creds but are not present. 
Jira: https://issues.redhat.com/browse/AAP-16634
> fix: handle import error with missing creds - AAP-16634

- tools/docker/docker-compose-stage.yaml
Docker-compose-stage should be closer to prod env running gunicorn and daphne instead of runserver. 
jira: https://issues.redhat.com/browse/AAP-16846
> ci: AAP-16846 - run eda server stage with gunicorn and daphne

- tools/docker/docker-compose-dev.yaml
- tools/docker/docker-compose-stage.yaml
Follow up https://github.com/ansible/eda-server/pull/407
In podman rootless the volume works out of the box because usually the host user is also 1000. 
In docker rootful hosts the path is mount as root so we need to change the owner. This affects the GitHub runners which has by default docker. 
We could address this issue running the docker-compose with podman instead docker, but in this way the docker-compose is more compatible without requiring podman.
> chore: make docker-compose docker rootful compat

- src/aap_eda/tasks/project.py
- tests/integration/conftest.py
- tests/integration/tasks/test_projects.py
In an environment with a default worker running, tests that enqueue tasks on the default queue  result in the task being executed by the default worker within the default worker's environment.  This causes a cross-environment issue for tests (e.g., test_projects) which depend on the executing task accessing the test environment's DB which results in test failure.  This change adds a test environment-specific queue (still referenced as 'default_queue' thereby providing a logically consistent facade) on which these tasks are run within the same environment as the test's DB.
> fix(test): Task queued execution in testing

- src/aap_eda/api/exceptions.py
- src/aap_eda/settings/default.py
- tests/integration/api/test_fallback_handler.py
Prevents stack trace on unexpected exceptions in deployment. If there is no already extant Response instance and debug is not enabled generates an internal server error Response containing contextual information as to the origin of the exception (what api and parameters were specified).
> (chore) Add api fallback exception handler.

- src/aap_eda/settings/default.py
The default -1 for timeout will let the activation job run without a timeout for long running activation.
Fixes AAP-17613: Activations die after running for approx 12 minutes
> Set default timeout for queues using unix socket

- Taskfile.dist.yaml
formatters executed by pre-commit don't need to just advise to fix the issues manually. Let's do it at the same time.
> chore: remove --check flag for isort and black

- src/aap_eda/services/project/git.py
- tests/unit/test_git.py
Disable "shell=True" for the subprocess executor and refactor the way to prevent password leaks. 
Includes:
- Undo the "GIT_PASSWORD" environment variable.  Passwords are again passed directly on the cmdline but removed from messages when catching the exception. 
- Implement a concrete exception for authentication errors. 
- Minor fix in the clone method which is a class method but returned GitRepository class instead. 
- Update and add new tests. 
Jira: https://issues.redhat.com/browse/AAP-17778
> fix: disable shell mode for git executor AAP-17778

- src/aap_eda/services/activation/db_log_handler.py
- src/aap_eda/services/activation/engine/common.py
- src/aap_eda/services/activation/engine/podman.py
split method can fail at unpacking if there is a log line without real content (like "\n")
also the current approach adds a second for the "since" value, in that second we might lose records. "since" is compatible with datetimes. 
Also fixes type hints
> fix: fix update logs podman

- src/aap_eda/services/activation/engine/ports.py
- tests/integration/services/activation/engine/test_ports.py
Port as string is usually supported in ansible. We should support customer plugins that support it.
> feat: support port as string

- src/aap_eda/api/views/activation.py
The view should not increase the restart counter because it doesn't know yet if is restartable or is effectively restarted. The counter should be increased by the manager only when the activation was actually restarted.
> fix: remove increase restart count from the view

- src/aap_eda/api/serializers/activation.py
- tests/integration/api/test_activation.py
The second `errors` is changed to `field_errors`. Now the validation error looks like:
```
{
"errors": {
"field_errors": "No controller token specified"   
}
}
```
Resolves [AAP-18000](https://issues.redhat.com/browse/AAP-18000)
> [AAP-18000] chore: change validation errors format

- src/aap_eda/services/activation/manager.py
Update the status of activation from `Stopping` to `Stopped` when it's disabled without instances.
> refactor: update activation status when stopping it without the instance

- tools/docker/docker-compose-mac.yml
The API service becomes unresponsive when we push a lot of events/rules from multiple running activations
Based on PR https://github.com/ansible/eda-server/pull/495
> chore: split the ws service in mac

- src/aap_eda/services/activation/engine/podman.py
- tests/integration/services/activation/engine/test_podman.py
Add these logs in activation instance db logs when activation is stopped.
```
......
ACTIVATION BEING STOPPED AT USER REQUEST
......
......
Container 936b3632680df33b257bf0e6077ba72687df970a6e8f0dd6f94c275f233b98ae exited with 143.
Container 936b3632680df33b257bf0e6077ba72687df970a6e8f0dd6f94c275f233b98ae is cleaned up.
```
> refactor: add container exit code in podman

- src/aap_eda/services/activation/manager.py
- src/aap_eda/settings/default.py
Add prefix (default from settings) to the podman containers. The default container name looks like: `eda-3-c48e6107-b531-46e6-b6e4-fbc0f7b2b145`
> refactor: add default prefix to podman containers

- src/aap_eda/services/activation/db_log_handler.py
- src/aap_eda/services/activation/engine/common.py
- src/aap_eda/services/activation/engine/kubernetes.py
- src/aap_eda/services/activation/engine/podman.py
- src/aap_eda/services/activation/manager.py
- src/aap_eda/settings/default.py
- tests/integration/services/activation/engine/test_podman.py
Add timestamp choice in log writer. When turn it on, the message logged look like:
```
2023-11-09 21:08:24,244 Pulling image quay.io/ansible/ansible-rulebook:main
2023-11-09 21:08:24,971 Starting Container
2023-11-09 21:08:24,973 Container args ['ansible-rulebook', '--worker', '--websocket-ssl-verify', 'no', '--websocket-address', 'ws://host.containers.internal:8000/api/eda/ws/ansible-rulebook', '--id', '6', '--heartbeat', '300', '-v']
2023-11-09 21:08:25,054 Container 1cd965b5f50853196f12a555f44e0cf599937b48d68482c15e5dc23e479540fe is started.
2023-11-09 21:08:25,325 - ansible_rulebook.app - INFO - Starting worker mode
2023-11-09 21:08:25,325 - ansible_rulebook.websocket - INFO - websocket ws://host.containers.internal:8000/api/eda/ws/ansible-rulebook connecting
```
Also, fix the typo in …
> refactor: add timestamp flag in log writer

- src/aap_eda/api/serializers/activation.py
- src/aap_eda/api/views/activation.py
- tests/integration/api/test_activation.py
As discussed with @lgalis, we keep the validation error format as it is, and UI will decide how to display it to the end users.
This is also a follow-up with https://github.com/ansible/eda-server/pull/492.
Resolves: [AAP-18000](https://issues.redhat.com/browse/AAP-18000)
> [AAP-18000] Restore non_field_errors key in validation errors

- src/aap_eda/core/management/commands/update_password.py
- tests/unit/commands/test_update_password.py
- Adds a new django-admin command `update_password` to update the given user's password
Solves: [AAP-11699](https://issues.redhat.com/browse/AAP-11699)
> [AAP-11699] Add update_password command

- tools/docker/docker-compose-dev.yaml
Follow up: https://github.com/ansible/eda-server/pull/495
The service should use by default the local development image.
> chore: fix image of eda-ws pod in docker dev

- scripts/eda_kube.sh
❯ task minikube:logs:eda
task: [minikube] scripts/eda_kube.sh eda-logs 
Defaulted container "eda-api" out of: eda-api, wait-for-postgres (init)
error: you are attempting to follow 8 log streams, but maximum allowed concurrency is 5, use --max-log-requests to increase the limit
task: Failed to run task "minikube:logs:eda": exit status 1
>  chore: increase max-log-requests on task minikube:logs:eda

- src/aap_eda/api/views/activation.py
This PR removes the unused model mixins from Activation since we have manually implemented `create`, `retrieve` and `list` methods on Activation viewset.
> chore: remove unused mixins from Activation

- src/aap_eda/services/activation/engine/kubernetes.py
- src/aap_eda/services/activation/engine/podman.py
- src/aap_eda/services/activation/manager.py
There is no reason to duplicate code among engines. Instead catch the exception and write the logs only once in the manager.
> refactor: ignore errors in update logs and cleanup

- src/aap_eda/wsapi/consumers.py
- src/aap_eda/wsapi/messages.py
- tests/integration/wsapi/test_consumer.py
When the ansible-rulebook is shut down, sending a 'Hello' message to it will raise writing to closed protocol exception, which causes unprocessed messages in the buffer to be ignored. So the audit rules were intermittently missing.
Linked: https://github.com/ansible/eda-server/pull/423
Resolves: [AAP-18690](https://issues.redhat.com/browse/AAP-18690)
> [AAP-18690] Remove sending Hello message to client when it's shutdown

- .github/workflows/ci.yaml
- README.md
- poetry.lock
- pyproject.toml
- Run tests for supported versions of python 3.9, 3.10, 3.11
- Pin versions in metadata
- Add nice looking badges. 
jira: https://issues.redhat.com/browse/AAP-13387
> chore: add matrix versions for ci until py3.11

- src/aap_eda/api/views/rulebook.py
- tests/integration/api/test_rulebook.py
This PR fixes a bug that was introduced with https://github.com/ansible/eda-server/pull/558, which in turn was causing e2e tests to fail with the following error
```
Calling QuerySet.filter() after union() is not supported.
```
Solves: [AAP-18894](https://issues.redhat.com/browse/AAP-18894)
> [AAP-18894] Update audit events endpoint to fix e2e tests

- src/aap_eda/services/project/git.py
- tests/unit/test_git.py
We have received several reports of timeouts occurring with large projects. Until we implement a feature allowing for a configurable timeout, we will increase the default hardcoded value to a more reasonable level.
Jira: https://issues.redhat.com/browse/AAP-19052
> chore: increase default timeout for git clone project

- src/aap_eda/services/activation/engine/messages.py
- src/aap_eda/services/activation/engine/podman.py
- tests/integration/services/activation/engine/test_podman.py
We are not handling all the possible states returned by podman. An existing container transitions to "stopping/stopped" status before being "exited".
Ensure we handle all the potential states from podman. 
Fixes https://issues.redhat.com/browse/AAP-19142
> fix: handle all potential states from podman

- tools/docker/docker-compose-dev.yaml
- tools/docker/docker-compose-mac.yml
Following exposed docker ports conflicts with other AAP services:
- 8000:
- conflicts with Gateway API
- configurable by ENV `EDA_API_PORT` (`EDA_API_PORT=8010 go-task docker:up`)
- 5432:
- conflicts with Gateway Postgres
- configurable by ENV `EDA_PG_PORT`
- 6379 Redis
- configurable by ENV `EDA_REDIS_PORT`
- 8001 WS
- configurable by ENV `EDA_WS_PORT`
- 8443 UI
- configurable by ENV `EDA_UI_PORT`
- 8888 Podman
- configurable by ENV `EDA_PODMAN_PORT`
> Fix port conflicts when running other Ansible dev environments

- poetry.lock
- pyproject.toml
Following the PR https://github.com/ansible/django-ansible-base/pull/55, we are now able to install DAB-related packages based on each feature (authentication, filtering, etc.). This PR changes DAB installation to reflect those changes. 
NOTE: If we want to use other features such as `filtering` from DAB in the future, we will need update pyproject.toml to include those features in extras.
> chore: update django-ansible-base dependency installation

- setup.cfg
- src/aap_eda/services/activation/engine/common.py
- src/aap_eda/settings/default.py
- tests/integration/services/activation/engine/test_kubernetes.py
- tests/integration/services/activation/engine/test_podman.py
Fix the type of podman mounts to avoid errors like:
```
aap_eda.tasks.orchestrator ERROR    [...] Reason Activation 20 failed to start. Reason: Container request is not valid.Errors: [{'loc': ('mounts',), 'msg': 'value is not a valid dict', 'type': 'type_error.dict'}]
```
Also ensures the id of the rulebookcmdline is always str. 
Update internal docs of settings accordingly.
Jira: https://issues.redhat.com/browse/AAP-19513
> fix: ensure types for podman mounts and rulebookcmdline

- tests/integration/services/activation/engine/test_podman.py
services/activation/podman.py uses XDG_RUNTIME_DIR; the tests need to as well in order to pass with it set.
> fix: tests respect setting of XDG_RUNTIME_DIR

- poetry.lock
- pyproject.toml
The current version of dynaconf [has an issue](https://github.com/dynaconf/dynaconf/issues/976) where only cast to boolean lowercase values, so EDA_DEBUG=false works as expected and EDA_DEBUG=False is set as a string and evaluated as a True. This means that users are deploying eda-server with debug enabled when it is not expected with all the impact over the security and performance matters. This has been detected in our downstream builds where the installer sets "EDA_DEBUG=False" by default. 
Also pin the ansible-base version due to a breaking change. 
Jira: https://issues.redhat.com/browse/AAP-19577
> chore: upgrade dynaconf dependency

- .github/workflows/ci.yaml
- README.md
- docs/contributing.md
- docs/development.md
- poetry.lock
- pyproject.toml
- tools/docker/Dockerfile
Make python3.11 the minimal supported version of python, required for incoming features and dependencies. 
Jira: https://issues.redhat.com/browse/AAP-19615
> chore: bump minimal python version to 3.11

- poetry.lock
- src/aap_eda/wsapi/routes.py
Due to recent restructure of dependency library django-ansible-base, `lib` was inserted into the package path.
> fix: importing package from ansible_base.lib

- src/aap_eda/wsapi/consumers.py
- tests/integration/wsapi/test_consumer.py
The empty job uuid will fail to update audit actions and events correctly to DB.
```
eda-ws_1                 | 2024-01-30 15:25:36,077 daphne.server ERROR    Exception inside application: ['"" is not a valid UUID.']
eda-ws_1                 | Traceback (most recent call last):
eda-ws_1                 |   File "/app/venv/lib64/python3.11/site-packages/django/db/models/fields/__init__.py", line 2688, in to_python
eda-ws_1                 |     return uuid.UUID(**{input_form: value})
eda-ws_1                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
eda-ws_1                 |   File "/usr/lib64/python3.11/uuid.py", line 178, in __init__
eda-ws_1                 |     raise ValueError('badly formed hexadecimal UUID string')
eda-ws_1                 | ValueError: badly formed hexadecimal …
```
> fix: handle empty job uuid in action messages properly

- src/aap_eda/wsapi/consumers.py
- src/aap_eda/wsapi/messages.py
- tests/integration/wsapi/test_consumer.py
This PR adds the logic to send vault-type credentials to the rulebook engine via WebSocket channels
Resolves: [AAP-19417](https://issues.redhat.com/browse/AAP-19417)
> feat: [AAP-19417] Enable to send vault credentials to rulebook

- src/aap_eda/wsapi/routes.py
The websocket is between eda-server and ansible-rulebook only.
https://issues.redhat.com/browse/AAP-20292
> Remove AllowedHostsOriginValidator

- .github/workflows/e2e-dispatch.yml
This workflow allows us to build eda-server from some branch and run on demand the private e2e test suite through the Actions tab in the UI.
It can be triggered against some PR if "run-e2e" label is added. 
It also has a variable to set a different ref for the test suite (main by default)
Warn, it might not work and need fixes, we need to merge it.
> ci: add workflow for e2e test run on demand

- .github/workflows/e2e-dispatch.yml
The workflow fails because it tries to pull a local image, we don't need to pull the images in this case so I deleted that line.
> ci: remove pull step in e2e on demand workflow

- src/aap_eda/api/resource_api.py
- src/aap_eda/api/urls.py
- src/aap_eda/settings/default.py
* implement resource_registry app from django-ansible-base
JIRA: [AAP-18826](https://issues.redhat.com/browse/AAP-18826)
> [AAP-18826] Integrate Resources API

- src/aap_eda/services/auth.py
Our existing code set an explicit password to the service user, which does not create a security concern because the password is not hashed, the `check_password()` always return `False`. This minor fix switches to use the built-in method `set_unusable_password()` which does the same thing but more elegant.
> chore: make token_service_user password unusable

- .github/workflows/e2e-dispatch.yml
When you add the label run-e2e to run the private test-suite, only is executed the time that the label is added. If later there are new commits it is not executed, forcing you to remove and re-add the label again. This PR wants to fix that, executing the workflow for any new commit if the label is present.
> ci: ensure run-e2e label always triggers workflow

- Taskfile.dist.yaml
- scripts/eda_kube.sh
- tools/deploy/eda-ui/service.yaml
Previously the minikube workflow required the UI and eda server images to be built locally before they can be used. Which is cumbersome, this PR adds a new task called
* quay-deploy
which allows us to run directly from quay images and it also allows for the images to be overridden for UI and eda server local images using the following env vars
* EDA_UI_IMAGE=localhost/eda-ui:latest
* EDA_UI_IMAGE_PULL_POLICY=Never
* EDA_IMAGE=localhost/eda-server:latest
* EDA_IMAGE_PULL_POLICY=Never
To run the minikube deployment run the following command
```
task minikube:quay-deploy
```
Once all the pods are up and running do a port forwarding
```
task minikube:fp:ui 
```
Now you should be able to access the running containers using the following URL **https://localhost:8443/**
To cleanup
```
task …
```
> chore: allow for minikube deployments to use quay images

- src/aap_eda/services/activation/engine/common.py
- src/aap_eda/services/activation/engine/factory.py
- src/aap_eda/services/activation/engine/kubernetes.py
- src/aap_eda/services/activation/engine/podman.py
- src/aap_eda/services/activation/manager.py
- tests/integration/services/activation/engine/test_kubernetes.py
https://issues.redhat.com/browse/AAP-20691
In K8S the resource prefixes are added to secret, service, job, and pod names to avoid conflicting resources for event streams and activations. They looks like:
> feat: Rename service name for event streams in k8s

- poetry.lock
- src/aap_eda/api/serializers/activation.py
- src/aap_eda/api/serializers/rulebook.py
- src/aap_eda/core/management/commands/create_initial_data.py
- src/aap_eda/core/migrations/0021_organization_team_and_more.py
- src/aap_eda/core/migrations/0022_add_default_organization.py
- src/aap_eda/core/models/__init__.py
- src/aap_eda/core/models/activation.py
- src/aap_eda/core/models/rulebook.py
This adds changes to managed roles in RBAC created by `create_initial_data` command to grant parent models to have permissions for their associated child models.
The models permission inheritance structure that are changed:
1. Activation -> Activation Instance -> Audit Rule
2. Project -> Rulebook
> Add permission inheritance for managed roles

- src/aap_eda/services/activation/engine/podman.py
- tests/integration/services/activation/engine/test_podman.py
https://issues.redhat.com/browse/AAP-21067
The pull image API has an additional keyword args that takes in the auth_config with the username and password.
> fix: remove writing to auth json file when pulling image in podman

- src/aap_eda/api/serializers/user.py
- tests/integration/api/test_user.py
* add 'is_superuser' field for POST /users/ endpoint, defaults to false
JIRA: https://issues.redhat.com/browse/AAP-21373
> chore: add 'is_superuser' field for POST /users/ endpoint

- src/aap_eda/services/activation/engine/ports.py
- src/aap_eda/settings/default.py
- tests/integration/services/activation/engine/test_ports.py
On the EDA Server side we try to open ports for port forwarding using the container engine (podman/k8s). We only allow a specific set of source plugins listed in the settings
**SAFE_PLUGINS_FOR_PORT_FORWARD** to be eligible for port forwarding. The default settings only supports the following source plugins
* ansible.eda.webhook
* ansible.eda.alertmanager
The user can augment this settings to include other source plugins
https://issues.redhat.com/browse/AAP-17416
> fix: allowlist for source plugins with port forward

- src/aap_eda/services/project/__init__.py
- src/aap_eda/services/project/imports.py
- src/aap_eda/tasks/project.py
- tests/integration/services/data/project-05-import.json
- tests/integration/services/data/project-05/extensions/eda/rulebooks/bad1.yml
- tests/integration/services/data/project-05/extensions/eda/rulebooks/bad10.yml
- tests/integration/services/data/project-05/extensions/eda/rulebooks/bad2.yml
- tests/integration/services/data/project-05/extensions/eda/rulebooks/bad3.yml
- tests/integration/services/data/project-05/extensions/eda/rulebooks/bad4.yml
- tests/integration/services/data/project-05/extensions/eda/rulebooks/bad5.yml
- tests/integration/services/data/project-05/extensions/eda/rulebooks/bad6.yml
- tests/integration/services/data/project-05/extensions/eda/rulebooks/bad7.yml
- tests/integration/services/data/project-05/extensions/eda/rulebooks/bad8.yml
- tests/integration/services/data/project-05/extensions/eda/rulebooks/bad9.yml
- tests/integration/services/data/project-05/extensions/eda/rulebooks/good.yml
- tests/integration/services/test_project_import.py
Validate db model required fields exist in the rulebook. Skip such rulebook and log a warning.
Also fix some selected exceptions prevent the import_state from changing to failed.
AAP-20868: Project import hangs when importing malformed rulebook
> fix: enhance rulebook validation during project import

- src/aap_eda/core/management/commands/create_initial_data.py
Sorry about this, these methods would take the class or the model_name and it very inconsistently did both internally. I tried to make these strictly model-argument as cleanup, but forgot to think about downstream effects.
> Fix changes in type expectation in DAB RBAC upstream

- .github/workflows/e2e-dispatch.yml
run-e2e label was executing the tests against HEAD of main instead of the PR. This PR tries to fix that.
> ci: fix the ref used in run-e2e label

- tests/integration/api/test_event_stream.py
The response contents are not necessarily in the order as the credentials were added.
> fix: sort credentials in test_retrieve_event_stream

- src/aap_eda/api/serializers/eda_credential.py
We had duplicate sections where the id, modified_at and created_at where both read and write fields.
> fix: id, and date time fields should be readonly

- src/aap_eda/api/serializers/eda_credential.py
The inputs in Eda-credential object should be an object and not a string
> Eda-credential inputs should be an object

- src/aap_eda/api/serializers/eda_credential.py
- tests/integration/api/test_eda_credential.py
When doing an updated inputs was being incorrectly marked as needed.
> fix: allow for updates without inputs

- src/aap_eda/api/filters/activation.py
- src/aap_eda/api/views/eda_credential.py
- tests/integration/api/test_activation.py
- tests/integration/api/test_credential.py
- tests/integration/api/test_eda_credential.py
We have this endpoint called 
```
f"{api_url_v1}/activations/?credential_id={eda_credential_id}"
```
This should have been called de_credential_id since in the backend we are just checking for DE's.
This will have to be changed to account for other credentials
For now we are trying to use the eda_credential_id
Support deletion of eda_credential based on forced=True option
> fix: support credential_id to local DE's using credential

- poetry.lock
- src/aap_eda/core/tasking/__init__.py
Fix errors when upgrade django-rq.
- Upgrade django-rq to 2.8
- Custom queue should inherit from django-rq. Ref: https://github.com/rq/django-rq?tab=readme-ov-file#custom-queue-classes
- Use named parameters at instantiation. 
Jira: https://issues.redhat.com/browse/AAP-21969
Probably rq can be upgraded as well with this change, but it's something that I want to test and change separately. 
Example error:
```Mar 20 15:56:23 ip-10-0-2-25 automation-eda-controller-activation-worker-4[110666]:    utility.execute()
Mar 20 15:56:23 ip-10-0-2-25 automation-eda-controller-activation-worker-4[110666]:  File "/usr/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
Mar 20 15:56:23 ip-10-0-2-25 automation-eda-controller-activation-worker-4[110666]: …
```
> fix: upgrade django-rq and fix queue and worker params

- .github/workflows/ci.yaml
Peeling off from https://github.com/ansible/eda-server/pull/761
This is a pain point for working on the `feature/rbac` branch. Unless this is doing something I don't know about, it should be a good idea to unconditionally run PR checks.
> [main] Run checks on PRs against any branch

- src/aap_eda/services/activation/engine/podman.py
Capture exceptions when purging volumes to handle wrong failed activations. 
Jira: https://issues.redhat.com/browse/AAP-22132
> fix: tolerate volume prune exception [AAP-22132]

- src/aap_eda/api/serializers/credential_type.py
- src/aap_eda/api/serializers/eda_credential.py
- src/aap_eda/api/views/credential_type.py
https://issues.redhat.com/browse/AAP-22394
The post body is changed as:
```
"CredentialTypeCreate": {
"type": "object",
"properties": {
"name": {
"type": "string"
},
"description": {
"type": "string"
},
"inputs": {
"type": "object",
"additionalProperties": {},
"description": "Name of the credential type"
},
"injectors": {
"type": "object",
"additionalProperties": {}
}
},
"required": [
"inputs",
"name"
]
},
```
> fix: remove unneeded required fields in credential type's post body

- .github/workflows/e2e-dispatch.yml
- .github/workflows/scheduled.yml
- GH deprecated the V1 docker-compose in ubuntu-latest https://github.com/actions/runner-images/issues/9557
- Switched to explicitly use V2 docker compose plugin instead
> ci: fix failing docker-compose step

- src/aap_eda/core/models/user.py
This change is needed to display user details in `summary_fields` in `/role_user_assignments/` endpoints as follows:
```
"summary_fields": {
"object_role": {
"id": 1
},
"role_definition": {
"id": 13,
"name": "Activation Admin",
"description": "Has all permissions to a single activation and its child resources - rulebook process, audit rule",
"managed": true
},
"user": {
"id": 3,
"username": "doston",
"email": "",
"first_name": "",
"last_name": null,
"is_superuser": false
}
},
```
> Add user summary fields to be displayed in role_user_assignments

- src/aap_eda/api/serializers/activation.py
When we create an activation for the first time, we update the extra vars with keys from the credentials. This check should happen only when the Activation is being created. We should not do the extra var key check during post activation otherwise we will always see the duplicates which are the keys we added during create.
> fix: check the duplicates in extra var only during create

- src/aap_eda/api/views/activation.py
- src/aap_eda/api/views/decision_environment.py
- src/aap_eda/api/views/eda_credential.py
- src/aap_eda/api/views/organization.py
- src/aap_eda/api/views/project.py
- src/aap_eda/api/views/rulebook.py
- src/aap_eda/api/views/team.py
- Remove `rbac_resource_type` params from views, since with the use of DAB RBAC library, `rbac_resource_type` param is no longer needed in views. 
- Replace `get_object_or_404` with `self.get_object` where necessary to make sure requests go through permission check.
> [RBAC] Remove unused rbac_resource_type params

- src/aap_eda/api/views/activation.py
- tests/integration/api/test_activation_instance.py
DELETE activation_instance endpoint was never needed and we have discussed several times to remove it but never got around to it. 
Jira: https://issues.redhat.com/browse/AAP-22555
> chore: remove DELETE activation_instance endpoint

- src/aap_eda/api/views/credential_type.py
- tests/integration/api/test_credential_type.py
When defining the fields for a Credential Type inputs if the user doesn't provide a type, set the type to be string
https://issues.redhat.com/browse/AAP-22587
> fix: If the user doesn't provide a type use string as default

- .dockerignore
- .github/workflows/e2e-dispatch.yml
The image was being built from the tools/docker directory which doesn't have the .dockerignore and the .git
directory was getting included in the image.
Moved the image build to be from the same directory that contains the .dockerignore
> chore: fix the image build for e2e tests

- src/aap_eda/core/utils/credentials.py
- tests/integration/api/test_eda_credential.py
We were using yaml dump which doesn't preserve the order of the keys by default. We have to pass in sort_keys=False so it can preserve the order of keys.
https://issues.redhat.com/browse/AAP-22638
> fix: preserve the order of the inputs

- src/aap_eda/api/serializers/fields/ansible_resource.py
- src/aap_eda/api/serializers/organization.py
- src/aap_eda/api/serializers/team.py
- src/aap_eda/api/serializers/user.py
- src/aap_eda/core/models/organization.py
- src/aap_eda/core/models/user.py
- tests/integration/api/conftest.py
- tests/integration/api/test_organization.py
- tests/integration/api/test_team.py
- tests/integration/api/test_user.py
- tests/integration/conftest.py
This adds `resource` field in Users, Organizations and Teams responses from API endpoints which will have JSON object format similar to the following:
```
"resource": {
"ansible_id": "f1434576-a0ec-4bff-b2eb-3da2a5ec18f3",
"resource_type": "shared.team"
},
```
Sample data from shared resource responses
Users
```
{
"id": 1,
"username": "admin",
"first_name": "admin",
"last_name": "",
"is_superuser": true,
"resource": {
"ansible_id": "d9ef64a5-524c-45bc-be86-f8c43196cc31",
"resource_type": "shared.user"
}
}
```
Organizations
```
{
"id": 1,
"name": "Default",
"description": "The default organization",
"resource": {
"ansible_id": "088eb81c-ba52-466f-be26-cb474e6e466d",
"resource_type": "shared.organization"
},
"created": "2024-04-11T15:59:54.744499Z",
"created_by": null,
"modified": …
```
> Add Resource metadata to users, orgs and teams responses

- src/aap_eda/api/urls.py
- src/aap_eda/core/urls.py
- tests/integration/core/test_views.py
Expose status endpoint inside api/v1
Jira: https://issues.redhat.com/browse/AAP-22421
> fix: enroute status path correctly

- src/aap_eda/services/activation/activation_manager.py
- src/aap_eda/services/activation/manager.py
- src/aap_eda/services/activation/status_manager.py
- src/aap_eda/tasks/orchestrator.py
- tests/integration/services/activation/test_manager.py
- tests/integration/tasks/test_orchestrator.py
Refactor the activation manager to move out the status management into a parent class "StatusManager". This is used when we want to change the status of activations in the orchestrator prior to the container livecycle. 
Jira: https://issues.redhat.com/browse/AAP-22452
> refactor: move out status management into StatusManager

- src/aap_eda/tasks/orchestrator.py
The log line looked like
```
Dispatching activation {process_parent_id} as new process.
```
> fix: missing f in string interpolation

- src/aap_eda/core/enums.py
- tests/integration/core/test_status_handler.py
The implementation of the `workers offline` status always set a status_message, but a default message must be defined for consistency. It updates the test to ensure always we have a default status message per each status.
> fix: add missing default status msg for workers_offline

- src/aap_eda/core/utils/credentials.py
- tests/unit/test_credential_validation.py
https://issues.redhat.com/browse/AAP-23311
The missing passphrase key error message is moved from the `SCM Private Key` field to the `Private Key Passphrase` field:
> fix: move validated error message under the right field

- tests/integration/api/test_eda_credential.py
https://issues.redhat.com/browse/AAP-23330
The issue comes from a typo on the UI side, here just add a test case.
> chore: add a test case for filter on eda credentials

- src/aap_eda/api/serializers/activation.py
- src/aap_eda/api/serializers/event_stream.py
- src/aap_eda/api/views/activation.py
- src/aap_eda/api/views/event_stream.py
- tests/integration/api/conftest.py
- tests/integration/api/test_activation_instance.py
- tests/integration/api/test_event_stream.py
Expose the queue name for the rulebook process, requested by QE. 
Jira: https://issues.redhat.com/browse/AAP-23289
> feat: add queue_name field to process instance views

- poetry.lock
- pyproject.toml
To be aligned with DAB, to bring this fix: https://github.com/encode/django-rest-framework/pull/8684
> chore: upgrade djangorestframework

- src/aap_eda/services/activation/engine/kubernetes.py
https://github.com/ansible/eda-server/issues/858
Remove the unneeded `created-by: eda` selector from the created service, so it has valid endpoints in the list, like:
```
» kubectl get endpoints -n aap-eda
NAME           ENDPOINTS                             AGE
aaa            10.244.0.153:5555,10.244.0.153:4444   4h59m
bbb            10.244.0.164:5555                     8m22s
eda-api        10.244.0.159:8000                     5h9m
eda-postgres   10.244.0.151:5432                     5h9m
eda-redis      10.244.0.152:6379                     5h9m
eda-ui         10.244.0.150:443                      5h9m
```
> fix: remove unneeded created_by selector from K8S service

- tests/integration/api/conftest.py
- tests/integration/api/test_decision_environment.py
- tests/integration/api/test_eda_credential.py
- tests/integration/api/test_project.py
- tests/integration/conftest.py
We need to have our tests connect the correct type of credentials to correct objects
* RH AAP and Vault types can only be connected to Activation
* Source Control and GPG Public key can only be connected to Project
* Container Registry can only be connected to Decision Environment
* Custom Credential types can only be connected to Activation
> test: connect the credentials to correct objects

- src/aap_eda/api/serializers/eda_credential.py
- src/aap_eda/api/views/eda_credential.py
- tests/integration/api/test_eda_credential.py
https://issues.redhat.com/browse/AAP-23509
1. allow to update name, or description when there is no `inputs` field in the payload;
2. allow to update the `inputs` field by extending data;
> fix: skip validating inputs to allow updating credentials' name or description

- src/aap_eda/services/project/scm.py
AAP-23633: SCM credentials without a newline at the end of the private key do not work
> fix: force a line end when recreate the ssh key file

- tests/integration/api/test_fallback_handler.py
- tests/integration/conftest.py
- tests/integration/dab_rbac/test_crud_permissions.py
- tests/integration/dab_rbac/test_organization.py
- tests/integration/test_sanity.py
Fixes https://github.com/ansible/eda-server/issues/881
Example test command:
```
py.test tests/integration/dab_rbac/ -k test_project_credential_access
```
Apply diff
```diff
diff --git a/src/aap_eda/api/views/project.py b/src/aap_eda/api/views/project.py
index 73e8e7a..a4b0d0f 100644
--- a/src/aap_eda/api/views/project.py
+++ b/src/aap_eda/api/views/project.py
@@ -169,6 +169,7 @@ class ProjectViewSet(
},
)
def partial_update(self, request, pk):
+        raise Exception('alan!')
project = self.get_object()
if "proxy" in request.data:
new_proxy = request.data["proxy"]
```
Now run test
```
================================================================================ test session starts ================================================================================
platform linux -- …
```
> Make debug setting true for tests

- src/aap_eda/core/utils/credentials.py
- tests/integration/api/test_eda_credential.py
https://issues.redhat.com/browse/AAP-23681
> fix: validate inputs payload to match with schema when creating/updating credentials

- Taskfile.dist.yaml
To fix:
❯ task docker:up
task: [docker] docker-compose -p eda -f tools/docker/docker-compose-dev.yaml up --detach
WARN[0000] Found orphan containers ([eda-podman-1 eda-eda-activation-worker-2 eda-eda-activation-worker-1 eda-podman-pre-setup-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
> chore: add remove-orphans on docker-purge task

- src/aap_eda/settings/default.py
There may be deployments where the WEBSOCKET_TOKEN_BASE_URL doesn't coincide with WEBSOCKET_BASE_URL. 
This PR allows to set a different value for WEBSOCKET_TOKEN_BASE_URL.
> feat: allow WEBSOCKET_TOKEN_BASE_URL setting

- src/aap_eda/api/serializers/credential_type.py
- src/aap_eda/core/utils/credentials.py
- tests/integration/api/test_credential_type.py
- tests/integration/conftest.py
https://issues.redhat.com/browse/AAP-23687
Raise 400 error if inputs/injectors payload are empty when creating/updating credential types.
> fix: validate inputs/injectors when creating/updating credential types

- src/aap_eda/settings/default.py
As per internal discussions, DEBUG setting can expose sensitive data, and we want to make sure it is correctly set. Support common strings and prevent to enable it accidentally.
> chore: enforce boolean type for settings.debug

- tools/docker/docker-compose-dev-redis-tls.yaml
Fix: 
❯ docker-compose -f docker-compose-dev-redis-tls.yaml start
validating /home/mmagnani/Workspace/redhat/ansible/eda/eda-server/tools/docker/docker-compose-dev-redis-tls.yaml: services.redis.command.4 must be a string
> chore: fix services.redis.command.4 must be a string

- src/aap_eda/api/views/dab_decorate.py
https://issues.redhat.com/browse/AAP-22846
This PR changes the request body of PUT action for `/role_definitions/:id/` from RoleDefinitionDetail to RoleDefintionCreate.
> fix: change request body of update to role_definition_create

- src/aap_eda/services/activation/activation_manager.py
In https://github.com/ansible/eda-server/pull/916 I introduced a bug making the creation of the activation instance an atomic operation, we call inside the operation the "set_status" as part of the check for new processes and raise an exception, so when the check is true, the transaction is undone and the activation remains in "starting" status. 
Jira: https://issues.redhat.com/browse/AAP-25010
> fix: fix wrong atomic operation when create activation instance. 

- src/aap_eda/core/management/commands/wait_for_migrations.py
- tests/unit/commands/test_wait_for_migrations.py
`aap-eda-manage wait_for_migrations -t 60`
Replaces https://github.com/ansible/eda-server/pull/925
> feat: add "wait_for_migrations" command

- src/aap_eda/tasks/orchestrator.py
- tests/unit/test_orchestrator.py
The current implementation always gives priority to the first queue configured. 
If there are multiple candidates, returns one randomly.
> feat(dispatcher): return random queue with multiple candidates

- src/aap_eda/settings/default.py
We have noticed that the lock mechanism in the scheduler is not 100% reliable and when multiple schedulers are executed at the exact same time they can duplicate the jobs. Set the job_id to a static value so we can make sure we schedule always only one job. 
Jira: https://issues.redhat.com/browse/AAP-25019
> fix: set job id for scheduled jobs

- tools/docker/docker-compose-mac.yml
The current redis image doesn't match the chip architecture on M1 Macs and uses amd64 instead of arm64. Also we are seeing periodic shutting down of redis.
> chore: the redis image should match the architecture

- src/aap_eda/core/tasking/__init__.py
- src/aap_eda/settings/default.py
Follow up https://github.com/ansible/eda-server/pull/897
and https://github.com/ansible/eda-server/pull/926
As per internal discussions, we agreed to make the redis_prefix a static configuration. Using the service_id as the redis_prefix is problematic because the value is obtained from the database after migrations, but we need it during the early initialization of the application. This reverses the expected order of startup dependencies and causes problems with commands that should not require a DB connection, such as "collectstatic". Additionally, a meaningless prefix makes debugging much more difficult.
EDA is the only component following this pattern, with this PR it is in line with other components where the prefix is a static setting. 
Internal ref: …
> fix: make redis_prefix static config

- .pre-commit-config.yaml
- Taskfile.dist.yaml
Related to https://github.com/ansible/aap-gateway/pull/422
This changes things so that you can use `go-task` within the normal development flow. I wound up disabling this stuff locally to get by. Most things still work like `go-task docker:up:minimal`, but the pre-commit stuff is probably the most painful item here with no other obvious solution without code changes.
> Allow using go-task instead of task

- src/aap_eda/api/metadata.py
- src/aap_eda/api/serializers/rulebook.py
- tests/integration/dab_rbac/test_crud_permissions.py
requested by [AAP-25195](https://issues.redhat.com/browse/AAP-25195)
> fix: add GET to OPTIONS

- src/aap_eda/settings/default.py
- src/aap_eda/wsapi/consumers.py
- src/aap_eda/wsapi/messages.py
- tests/integration/wsapi/test_consumer.py
With the advent of controller behind our server the URL to access the job details for JobTemplate and WorkflowTemplate has changed
We have an api end point that is specificed in the RH AAP Credential Type this is sent to the ansible-rulebook so that it can talk to the controller via the api. This end point could point to a controller directly or to a controller behind our server.
To directly access the controller we only need the host and port so the API end point would look like
e.g. https://<<your_controller>>/
This will map the Job URL for a Job Template to look like
https://<<your_controller>>/#/jobs/playbook/23/details/
This will map the Job URL for a Workflow Template to look like
https://<<your_controller>>/#/jobs/workflow/24/details/
When the controller is behind our server the …
> fix: build the JOB URL on the server side

- src/aap_eda/core/models/credential_type.py
- src/aap_eda/core/models/decision_environment.py
- src/aap_eda/core/models/eda_credential.py
- src/aap_eda/core/models/event_stream.py
- src/aap_eda/core/models/rulebook.py
It helps to reverse the url to access the resource
Needed by https://github.com/ansible/django-ansible-base/blob/devel/ansible_base/lib/abstract_models/common.py#L21
AAP-25487: Role user assignment response missing content_object except for Activations
> fix: add router_basename for models with compound words

- src/aap_eda/core/models/rulebook_process.py
Follow up #949. It does not affect AAP-25487, but nice to point RuleBookProcess to its correct basename
> fix: add router-basename for RulebookProcess

- src/aap_eda/settings/default.py
This PR aims to resolve the following error when logging in as a user with global roles, such as system auditor. 
JIRA: [AAP-25834](https://issues.redhat.com/browse/AAP-25834)
> fix: add setting to enable global roles for users

- .github/workflows/e2e-dispatch.yml
We have issues with multinode pipeline because the workers are not ready in time and the test suite reaches the timeout when importing the project. The issue has become more frequent after https://github.com/ansible/eda-server/pull/957
Increase the timeout for this pipeline to avoid false negatives. With ~60 seconds could be good enough but with 120 we get protected when the GH performance is particularly bad.
> ci: increase timeout for multinode tests

- src/aap_eda/api/views/user.py
- tests/integration/api/test_user.py
This PR considers the following 3 new cases in users list view:
1. `?is_superuser=true` - returns only superusers
2. `?is_superuser=false` - returns only non-superusers
3. no query param - returns all the users
> feat: add filtering for superusers in users list view

- src/aap_eda/settings/default.py
Fix error:
```
Bad API request: 500 Server Error: Internal Server Error for url: https://service-provider:443/api/eda/v1/service-index/metadata/
```
Caused by:
```
rest_framework.request.WrappedAttributeError: 'Settings' object has no attribute 'ANSIBLE_BASE_JWT_MANAGED_ROLES'
```
We use `ansible_base.jwt_consumer` as [auth class](https://github.com/ansible/eda-server/blob/main/src/aap_eda/settings/default.py#L324) but is not installed the app. DAB requires it since [this commit](https://github.com/ansible/django-ansible-base/commit/6b80ced7506ebb3b7c2dafb48a018159dee997a8#diff-13662d6a6c68265823b74106f51995610e9f4157b5c4bfb3af3a7678e478e89dR155). 
Jira: https://issues.redhat.com/browse/AAP-26954
> fix: install ansible_base.jwt_consumer app

- tools/docker/docker-compose-dev-redis-tls.yaml
- tools/docker/docker-compose-dev.yaml
- tools/docker/docker-compose-mac.yml
- tools/docker/docker-compose-stage.yaml
The migration check was added in PR #957 to make podman-compose handle dependent containers coming up before the DB was ready. This check causes podman-compose/podman to terminate containers if they dont respond within 10 seconds. So reverting for now till we can come up with other solution to solve this for podman-compose
> chore: undo the migration check

- tests/integration/services/test_project_import.py
suppress warning: PytestCollectionWarning: cannot collect test class 'TestTempdirFactory' because it has a __init__ constructor (from: tests/integration/services/test_project_import.py)
Add `__test__ = False` to tell pytest to skip a class that does not contain any tests
> chore: suppress a pytest warning for a non-test class

- tools/docker/docker-compose-dev-redis-tls.yaml
- tools/docker/docker-compose-dev.yaml
- tools/docker/docker-compose-mac.yml
- tools/docker/docker-compose-stage.yaml
All of our workers have a dependency on the api-worker which has dependency to postgres and redis.
We dont need to have default worker and activation workers have a direct dependency to postgres and redis. They can have a direct dependency to api-worker.
In podman with the --requires if we have a direct dependency to redis and postgres from default and activation workers they might come up before even redis is queued up and break the dependency chain. Causing them to not start.
```
[eda-scheduler]         | Error: unable to start container c979979377dd402dacee7856328c205810362bf3abdb5c85d0e291ecb2ca6e45: generating dependency graph for container c979979377dd402dacee7856328c205810362bf3abdb5c85d0e291ecb2ca6e45: container 4f8bfe666edea37dd185d51066e09d5fcb512db3dcd2608f3acc2b5f106f9ad9 …
```
> chore: fix dependency for podman

- src/aap_eda/api/urls.py
- tests/integration/api/test_openapi.py
Currently only works https://localhost:8443/api/eda/v1/docs, docs/ returns 404
This PR fixes the correct handling of the trailing slash to keep it consistent with the rest of the application, so /docs is a 301 to -> /docs/ and /docs/ works as expected
Also adds sanity tests for all these urls.
> fix: correct trailing slash for api docs endpoints and update tests

- src/aap_eda/services/project/imports.py
- src/aap_eda/services/project/scm.py
- tests/unit/test_scm.py
The project import status is currently reported as failed when the project repo is empty; This PR changes the status of the project import to completed in such a scenario.
JIRA: [AAP-27994](https://issues.redhat.com/browse/AAP-27994)
> fix(AAP-27994): update import status to completed on empty project

- src/aap_eda/api/views/webhook.py
- src/aap_eda/settings/default.py
- tools/docker/docker-compose-dev.yaml
- tools/docker/docker-compose-mac.yml
- tools/docker/docker-compose-stage.yaml
As per internal discussions, rename WEBHOOK_URL_PREFIX to WEBHOOK_BASE_URL for a more meaningful variable name. 
Also ensure the trailing slash for the correct processing of the final url. 
Jira: https://issues.redhat.com/browse/AAP-28755
> chore(AAP-28755,AAP-28761): rename webhook prefix and ensure trailing slash

- poetry.lock
- pyproject.toml
- src/aap_eda/core/tasking/__init__.py
- src/aap_eda/settings/default.py
- tests/conftest.py
- tests/integration/conftest.py
- tests/integration/core/test_tasking.py
This change uses the DAB-provided Redis client support which encapsulates requisite HA capabilities.
It does not currently take specific advantage of these capabilities; that is to come later.
> AAP-27921 Use DAB-provided Redis client.

- src/aap_eda/services/activation/engine/podman.py
- tests/integration/services/activation/engine/test_podman.py
This minor change updates the log output for podman deployments so that it is similar to what is printed in k8s deployments. This improves parity between deployments and enables us to easily test log output across the different deployment types.
Equivalent log output in k8s: https://github.com/ansible/eda-server/blob/bc35a0c6b04751caa7d1197aa734ef0d9df58877/src/aap_eda/services/activation/engine/kubernetes.py#L130
> fix: align log output between deployment types

- src/aap_eda/api/serializers/eda_credential.py
- tests/integration/api/test_eda_credential.py
https://issues.redhat.com/browse/AAP-29049
The UI will raise a warning as shown in the screenshot. Because we support the `force` flag, the deletion will succeed after checking `Yes`.
> feat (AAP-29049) - before deleting credentials check if event streams attached

- src/aap_eda/core/management/commands/create_initial_data.py
- tests/integration/conftest.py
- tests/integration/core/test_create_initial_data.py
- tests/integration/dab_rbac/test_managed_roles.py
- remove member_organization permission from org admin role
- add tests for role user and team assignments for managed org roles
JIRA: [AAP-29090](https://issues.redhat.com/browse/AAP-29090)
> fix(AAP-29090): remove member_organization permission from org admin role

- .github/workflows/ui-e2e.yml
- tools/docker/docker-compose-dev.yaml
This PR adds a new github workflow to run UI e2e tests on outstanding PRs on demand, similar to how EDA API e2e tests currently run. 
JIRA: [AAP-29098](https://issues.redhat.com/browse/AAP-29098)
> chore(AAP-29098): add UI e2e tests to github workflows

- .gitignore
- src/aap_eda/api/views/activation.py
- src/aap_eda/api/views/decision_environment.py
- src/aap_eda/api/views/mixins.py
- src/aap_eda/api/views/project.py
- src/aap_eda/api/views/webhook.py
- src/aap_eda/core/utils/logging_utils.py
Description: Adds CRUD logging messages to core EDA resources.
Jira: https://issues.redhat.com/browse/AAP-29258
**Rulebook Activations** Logging added for following operations- 
1. Create
2. Read
3. Update
4. Delete
5. ListActivations
6. Enable
7. Disable
8. Restart
**Decision Environments** Logging  added for following operations- 
1. Create
2. Read
3. Update
4. Delete
**Project** Logging added for following operations-
1. Create
2. Read
3. Update
4. Delete
5. Sync
EventStreams Logging added for following operations -
1. Create
2. Read
3. Update
4. Delete
5. List
6. ListActivations
Rulebook Activation Start/Stop/Restart (Already exists)
1. [Activation Start](https://github.com/ansible/eda-server/blob/main/src/aap_eda/services/activation/activation_manager.py#L651)
1. Has many [log …
> feat: Add CRUD log messages

- .github/workflows/ui-e2e.yml
This PR updates the env variable name to run EDA UI e2e tests, in order to correlate with the new name in ui-e2e image. 
cc @jamestalton
> fix: change env variable name to trigger EDA UI e2e tests

- tests/integration/api/test_user.py
This is an enabling PR to fix downstream test failures so we can clear the way for https://github.com/ansible/django-ansible-base/pull/562, which changes the default behavior so you can't create custom roles with non-read permissions to shared resources.
The `org_admin_rd` role was returning effectively a custom role, but we really don't want to allow creating this sort of custom roles.
> Change fixtures to managed roles to work with expected validators

- src/aap_eda/api/serializers/activation.py
- tests/integration/api/test_activation_with_credential.py
- tests/integration/conftest.py
https://issues.redhat.com/browse/AAP-29630
> fix: (AAP-29630) - save extra_var when creating an activation with vault/AAP credentials

- src/aap_eda/api/views/project.py
- tests/integration/api/test_project.py
Aligns "pre-flight" checking across requests that depend on redis.
> fix: perform project create request validation before redis check

- src/aap_eda/api/views/eda_credential.py
- src/aap_eda/core/utils/credentials.py
- tests/integration/api/test_eda_credential.py
https://issues.redhat.com/browse/AAP-29642
> fix: (AAP-29642) - Fix to save encrypted string in credentials

- src/aap_eda/api/serializers/activation.py
- tests/integration/api/test_activation.py
- tests/integration/wsapi/test_consumer.py
https://issues.redhat.com/browse/AAP-29728
Add `ruleset_stats` to the Activation `Read` view `api/eda/v1/activations/:id` only.
> feat: (AAP-29728) - Add ruleset_stats to activation read view

- README.md
- docs/contributing.md
As a part of the [Consolidating Ansible discussion platforms initiative](https://forum.ansible.com/t/proposal-consolidating-ansible-discussion-platforms/6812), this PR adds the communication section template defined by the community to the README and the docsite. Similar PRs are now being raised across all the Ansible ecosystem projects.
Thanks!
> Update communication links

- src/aap_eda/api/serializers/eda_credential.py
- tests/integration/api/test_eda_credential.py
https://issues.redhat.com/browse/AAP-29615
Change credential_type_id as required when creating credentials, and return a 400 error if it's missed.
> fix: (AAP-29615) 500 error when creating a credential with a none credential type id

- src/aap_eda/api/serializers/activation.py
- tests/integration/api/test_activation.py
- tests/integration/api/test_activation_with_credential.py
- tests/integration/services/activation/test_manager.py
https://issues.redhat.com/browse/AAP-30118
After the fix, the error message looks like this:
Previously it looked like
> fix:  (AAP-30118) - remove awx token from error message

- poetry.lock
- pyproject.toml
httpie should be placed in our testing dependancies, not in our overall deps.
This was a miss, and this PR is correcting this behavior.
> Move httpie to testing dependancies

- src/aap_eda/settings/default.py
This will add a new setting "MQ_TLS" to force TLS on for Redis connections. 
The default value for this setting is 'False'.  Switching it to 'True' will force TLS to be used for Redis connections.
The current logic of enabling TLS when provided a client certificate remains.
> Add setting to force TLS on for Redis connections

- src/aap_eda/core/management/commands/create_initial_data.py
- src/aap_eda/settings/default.py
- tests/integration/dab_rbac/test_related_permissions.py
This PR updates managed Use roles (e.g. Decision Environment Use) to limit their capabilities and avoid granting unwanted permissions. 
JIRA: [AAP-30640](https://issues.redhat.com/browse/AAP-30640) & [AAP-30627](https://issues.redhat.com/browse/AAP-30627)
> fix(AAP-30640): update use roles to mitigate permission escalation

- src/aap_eda/settings/default.py
- tests/unit/test_settings.py
Adds settings to EDA allowing manipulation of timeouts and retries for Redis cluster deployments.
> [AAP-30722] add Redis cluster-related retry and timeout settings

- src/aap_eda/settings/default.py
gunicorn sends a signal 6 when it is about to timeout a request This middleware handles that request and logs a traceback.
this aids in debugging infrastructure issues that may be causing requests to timeout.
> enable middleware to log traceback on timeout

- tools/deploy/eda-api/deployment.yaml
- tools/docker/docker-compose-dev-redis-tls.yaml
- tools/docker/docker-compose-dev.yaml
- tools/docker/docker-compose-mac.yml
- tools/docker/docker-compose-stage.yaml
I confirmed with @relrod that official installers set the environment variable `ANSIBLE_REVERSE_RESOURCE_SYNC` False when running the create_initial_data command. We could change the command itself, but I don't think we did this for any AWX commands, and in any case, I only want to modify `tools/` and not `src/` at this particular moment.
Adding that env var fixes this error for me:
```
File "/app/venv/lib64/python3.11/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 88, in execute
return super().execute(*args, **options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/venv/lib64/python3.11/site-packages/django/core/management/base.py", line 458, in execute
output = self.handle(*args, **options)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> [Hold] Consistency fixes to -dev compose file for aap-dev

- src/aap_eda/services/activation/engine/podman.py
- tests/integration/services/activation/engine/test_podman.py
https://issues.redhat.com/browse/AAP-31349
Based on [podman doc](https://docs.podman.io/en/latest/markdown/podman-login.1.html), we don't need the login in our scenario.
> fix: remove client login when using self certs

- poetry.lock
- pyproject.toml
- src/aap_eda/analytics/analytics_collectors.py
- src/aap_eda/analytics/collector.py
- src/aap_eda/analytics/package.py
- src/aap_eda/analytics/utils.py
- src/aap_eda/conf/registry.py
- src/aap_eda/core/management/commands/gather_analytics.py
- src/aap_eda/settings/default.py
- tests/integration/analytics/test_analytics_collectors.py
- tests/integration/analytics/test_gather_analytics.py
- tests/integration/analytics/test_utils.py
- tests/unit/test_application_settings.py
https://issues.redhat.com/browse/AAP-30754
replace https://github.com/ansible/eda-server/pull/1048
depends: https://github.com/ansible/eda-server/pull/1049
> feat: AAP-30754 - Add analytics collector to EDA

- src/aap_eda/settings/default.py
I kept hitting this error even when it should have been fixed:
```
File "/app/venv/lib64/python3.11/site-packages/ansible_base/resource_registry/signals/handlers.py", line 103, in sync_to_resource_server_post_save
sync_to_resource_server(instance, action)
File "/app/venv/lib64/python3.11/site-packages/ansible_base/resource_registry/utils/sync_to_resource_server.py", line 73, in sync_to_resource_server
client = get_resource_server_client(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/venv/lib64/python3.11/site-packages/ansible_base/resource_registry/rest_client.py", line 26, in get_resource_server_client
return ResourceAPIClient(
^^^^^^^^^^^^^^^^^^
File "/app/venv/lib64/python3.11/site-packages/ansible_base/resource_registry/rest_client.py", line 66, in __init__
self.base_url = …
```
> Use DAB value as fallback value for service path setting

- poetry.lock
Update twisted dependency in poetry.lock for the patch of CVE-2024-41810
This keeps upstream aligned with downstream deps.
Also includes the updates from https://github.com/ansible/eda-server/pull/953 
Jira: https://issues.redhat.com/browse/AAP-32258
> chore: update twisted and other deps in poetry lock

- src/aap_eda/settings/default.py
What I got merged in https://github.com/ansible/eda-server/pull/1059 was necessary, but didn't process everything that we needed. This should have been obvious to me, but the way I was testing didn't make everything immediately break at the time.
I'm trying to use a new method with `settings.exists` here, which I think it way way nicer than catching `NameError`. I haven't tested that it works with env vars (I'm pretty sure it will), but I'll try to post a confirmation of that soon.
> Add support for some more missing settings

- tools/docker/docker-compose-mac.yml
Mac equivalent PR of - https://github.com/ansible/eda-server/pull/1071
Removes eda-ui in favor of nginx on mac docker-compose
> chore: (mac) replace deprecated standalone eda-ui image with nginx

- src/aap_eda/analytics/analytics_collectors.py
- src/aap_eda/analytics/collector.py
- src/aap_eda/conf/registry.py
- src/aap_eda/core/management/commands/gather_analytics.py
- src/aap_eda/settings/default.py
- src/aap_eda/tasks/analytics.py
- tests/integration/tasks/test_analytics.py
- tests/unit/test_application_settings.py
Run the task with internval set to AUTOMATION_ANALYTICS_GATHER_INTERVAL. Admin is able to change the interval and auto reschedule without restart
AAP-31635: Create a scheduler task to collect and send analytics data
> feat: add a periodic task to run gather_analytics

- src/aap_eda/api/serializers/event_stream.py
- tests/integration/api/test_event_stream.py
- tests/integration/api/test_event_stream_basic.py
- tests/integration/api/test_event_stream_ecdsa.py
- tests/integration/api/test_event_stream_hmac.py
- tests/integration/api/test_event_stream_oauth2.py
- tests/integration/api/test_event_stream_oauth2_jwt.py
- tests/integration/api/test_event_stream_token.py
https://issues.redhat.com/browse/AAP-30827
Raise validation error if the `event_stream_type` of event streams doesn't match with the `kind` attribute of its related `credential_type` during creating time.
> fix: [AAP-30827] - validate the event_stream_type with credential_type in creating event streams

- src/aap_eda/api/filters/event_stream.py
- tests/integration/api/test_event_stream.py
- tests/integration/conftest.py
AAP-30356: Allow filtering of event streams based on the test_mode flag
> fix: allow event streams be filtered by test_mode

- tools/docker/docker-compose-dev-redis-tls.yaml
- tools/docker/docker-compose-dev.yaml
- tools/docker/docker-compose-stage.yaml
The persisting data for podman was added just as enhancement to not download the DE's every time the environment is restarted. 
This is generating more problems than solutions specially supporting cross compatibility between podman and docker. Its benefit is debatable since many of our workflows already removes the volumes. Now, for a reason that I couldn't figure out 100% (and because I don't want to spend more time on it) GH workflows are failing running podman so several e2e tests fails due to error connections to the podman socket. 
So, I think the best solution is just remove the persisted data for podman and simplify its deployment.
> ci: remove podman data persistence for docker-compose

- src/aap_eda/services/project/scm.py
quote considers "/" safe by default.
> fix: use quote with safe="" for user/secret in urls

- .github/workflows/autoupdate-poetry.yml
There was some issues in the current pipeline to autoupdate the poetry.lock
I have simplified the workflow and tested from this repo to make sure it works. 
Example: https://github.com/ansible/eda-server/pull/1095
> ci: update autoupdate-poetry-lock workflow

- .github/workflows/build-image.yml
Reverts https://github.com/ansible/eda-server/pull/1104/
We can not use strategy here because the image must be built and pushed as multiplatform image, but here we are running different jobs with different platform and the last one overwrites the other. 
To support a multiplatform image built in split jobs more actions are needed that can be done in a different PR. Anyway this would be less critical. 
This reverts commit c9dd25b27e8a6d3e5ac450c13f29275952c0fcc1.
> Revert "ci: split by platform the build image workflow"

- src/aap_eda/analytics/analytics_collectors.py
- src/aap_eda/analytics/package.py
- src/aap_eda/analytics/utils.py
- tests/integration/analytics/conftest.py
- tests/integration/analytics/test_analytics_collectors.py
- tests/integration/analytics/test_gather_analytics.py
- tests/integration/analytics/test_utils.py
https://issues.redhat.com/browse/AAP-33453
The job stats data is collected and saved in the file `jobs_stats.json`. It looks like:
```
{
"8018": [
{
"job_id": "8018",
"type": "run_job_template",
"created_at": "2023-12-14T15:19:02.319506Z",
"status": "successful",
"url": "https://controller_1/#/jobs/playbook/8018/details/",
"install_uuid": "9509fade-acf8-4ff8-b5d1-6e58e01dceb9"
},
{
"job_id": "8018",
"type": "run_workflow_template",
"created_at": "2023-12-14T15:19:02.326503Z",
"status": "successful",
"url": "https://controller_2/#/jobs/workflow/8018/details/",
"install_uuid": "6e78176d-87ba-4837-9316-bf84660ca77d"
}
],
"8020": [
{
"job_id": "8020",
"type": "run_workflow_template",
"created_at": "2023-12-14T15:19:02.327547Z",
"status": "successful",
"url": …
```
> feat: [AAP-33453] - Collect the stats data of jobs which launched by the EDA

- src/aap_eda/analytics/analytics_collectors.py
- tests/integration/analytics/test_analytics_collectors.py
- tests/integration/conftest.py
https://issues.redhat.com/browse/AAP-32189
The collected data is stored at event_streams_by_activation_table.csv in the tar file. It looks like:
> feat: [AAP-32189] Collect event streams used by each activation

- src/aap_eda/analytics/analytics_collectors.py
- tests/integration/analytics/test_analytics_collectors.py
- tests/integration/conftest.py
https://issues.redhat.com/browse/AAP-32877
For each activation, we collect its `name, id, status, restart_count, failure_count, log_level, organization_id, created_at, ended_at` (empty for those active activations), `counts`, and `max_retry_count`.
The `activations_stats_table.csv` has following columns:
> feat: [AAP-32877] - Collect activations stats data

- src/aap_eda/api/metadata.py
- src/aap_eda/api/serializers/setting.py
- src/aap_eda/conf/registry.py
- tests/integration/api/test_application_setting.py
Add customized attributes to fields from GET and PATCH method in the return body from OPTIONS method. These can be used for UI to properly render them to customer.
This implemententation returns a format compatible with how the controller returns OPTIONS request.
AAP-33164: EDA settings API needs to provide Options method.
Sample output:
```
{
"name": "Setting",
"description": "",
"renders": [
"application/json",
"text/html"
],
"parses": [
"application/json",
"application/x-www-form-urlencoded",
"multipart/form-data"
],
"actions": {
"PATCH": {
"INSIGHTS_TRACKING_STATE": {
"type": "boolean",
"required": false,
"label": "Gather data for Automation Analytics",
"help_text": "Enables the service to gather data on automation and send it to Automation Analytics.",
"category": "System", …
```
> feat: enhance options for /settings/system/ API

- src/aap_eda/services/activation/activation_manager.py
The started_at used to be the instance created time, which is even before the DE is downloaded. The download time plus the container init time can exceed the default 30 seconds LIVENESS timeout window. This fix resets the started_at time to be at the moment after the container is initiated.
This fix should help to resolve the sporadic eda-qa's e2e test failures.
> fix: update activation instance's started_at

- src/aap_eda/services/project/imports.py
- src/aap_eda/services/project/scm.py
Need to distinguish a git checkout failure is due to a non-existing branch/tag/commit, or due to an empty repository. The raw error messages are very similar but we have set the project sync state to completed for the later case in an earlier fix. This fix identifies the first case and set the state to be failed.
AAP-29144: Project sync should report status as "failed" when using non-existent branch
Also refactor the existing code to use a proper error class instead of. an error message to identify the case for an empty repo.
Will add e2e tests for the two cases.
> fix: checking out a non-existing branch fails the project sync

- src/aap_eda/services/project/imports.py
- tests/integration/services/test_project_import.py
It helps to reset properly the import state and error message.
AAP-34744: Sync a previously failed project importing falsely changes the state to completed
> fix: continue to sync rulebooks when previous sync failed

- src/aap_eda/api/serializers/project.py
- src/aap_eda/api/views/project.py
Utilize project instance as input to project retrieve read serializer.
https://issues.redhat.com/browse/AAP-29995
---
The current EDA code when retrieving a project passes a dictionary as the `instance` of the instantiated read serializer.  In the context of a web browser request (`rest_framework. renderers.BrowsableAPIRenderer`) this results in the issues as described in https://issues.redhat.com/browse/AAP-29995.
One of these issues is the logging of
```
ansible_base.rbac.api.permissions INFO Object-permission check called with non-object <class 'rest_framework.utils.serializer_helpers.ReturnDict'> 
```
which occurs when constructing a `PATCH` section of the page.
The other is
```
File "/usr/lib/python3.11/site-packages/aap_eda/api/serializers/project.py", line 31, in get_proxy
if not …
```
> fix: retrieve project using web browser

- src/aap_eda/api/serializers/__init__.py
- src/aap_eda/api/serializers/eda_credential.py
- src/aap_eda/api/views/eda_credential.py
- tests/integration/api/test_eda_credential.py
This PR disallows changing Credential Type when updating an Eda Credential. 
1. Create a new Eda Credential with type Container Registry
2. Try patching the credential with a payload of just the `credential_type_id` corresponding to the RHAAP Credential Type
3. Assert Credential Type has not been changed
**NOTE**: The UI already disables updating Credential Type; this issue exists only on the API. 
JIRA: [AAP-34968](https://issues.redhat.com/browse/AAP-34968)
> fix: disallow updating credential type on credential patch endpoint

- src/aap_eda/api/serializers/credential_type.py
- src/aap_eda/api/views/credential_type.py
- src/aap_eda/core/utils/credentials.py
- tests/integration/api/test_credential_type.py
- tests/unit/test_credential_validation.py
https://issues.redhat.com/browse/AAP-35882
To parity with controllers, empty injectors/inputs are allowed when creating/updating credential types.
> feat: allow empty injectors/inputs in creating/updating credential types

- src/aap_eda/api/serializers/activation.py
- src/aap_eda/core/exceptions.py
- src/aap_eda/core/utils/credentials.py
- src/aap_eda/wsapi/consumers.py
- src/aap_eda/wsapi/messages.py
- tests/integration/api/test_activation_with_credential.py
- tests/integration/api/test_credential_type.py
- tests/integration/wsapi/test_consumer.py
- tests/unit/test_credential_validation.py
This borrows a feature from AAP Credential Types to send file content to ansible-rulebook which can be used with sources. In AAP the vars are called tower.filename.certfile In eda its called eda.filename.certfile.
https://docs.ansible.com/automation-controller/latest/html/userguide/credential_types.html Please read injector configuration
https://issues.redhat.com/browse/AAP-25518
> feat: Extend credentials to support file contents

- src/aap_eda/core/utils/credentials.py
- tests/integration/api/test_credential_type.py
Prevent users from mixing template keys
template : "{{ data }}"       <-- partially qualified
template.certfile: "{{ other_data }}"  <-- fully qualified
You can either use fully qualified keys which is recommended but you cannot mix partially qualified and fully qualified keys
https://issues.redhat.com/browse/AAP-25518
> feat: for file injectors prevent mixing of keys

- src/aap_eda/api/serializers/decision_environment.py
- src/aap_eda/api/views/decision_environment.py
https://issues.redhat.com/browse/AAP-36030
The current EDA code when retrieving a decision environment passes a dictionary as the instance of the instantiated read serializer. In the context of a web browser request (rest_framework. renderers.BrowsableAPIRenderer) this results in logging of the following...
```
ansible_base.rbac.api.permissions INFO Object-permission check called with non-object <class 'rest_framework.utils.serializer_helpers.ReturnDict'> 
```
To address this issue this change modifies the decision environment retrieve and decision environment read serializer code to utilize a decision environment instance as input to the read serializer.
> fix: retrieve decision environment using web browser

- src/aap_eda/core/utils/credentials.py
- src/aap_eda/core/validators.py
- tests/integration/api/test_activation.py
- tests/integration/api/test_credential_type.py
Prevent users from using reserved attribute names when creating extra vars which are
1. eda
2. ansible
* eda is used when we create file name for injectors e.g "{{ eda.filename.certfile }}"
* ansible is used by ansible rulebook to send events to extra vars Controller e.g ansible.eda.events
We check the extra_vars in Activation as well as extra_vars in Credential Type injectors for reserved names
https://issues.redhat.com/browse/AAP-25518
> feat: prevent ansible, eda keys to be used in extra vars

- src/aap_eda/api/views/eda_credential.py
- src/aap_eda/core/enums.py
- src/aap_eda/core/utils/credentials.py
- tests/integration/api/test_eda_credential.py
- tests/integration/conftest.py
This PR adds a new endpoint `/eda-credentials/<id>/copy` to create a new copy of the given EDA Credential.
JIRA: [AAP-35878](https://issues.redhat.com/browse/AAP-35878)
> feat: [AAP-35878] add copy endpoint for EDA Credentials

- src/aap_eda/services/activation/db_log_handler.py
- tests/integration/services/activation/engine/test_podman.py
https://issues.redhat.com/browse/AAP-36058
Correct the default value of log_timestamp with the right timestamp.
> fix: [AAP-36058] correct the default log_timestamp of RulebookProcessLog records

- src/aap_eda/api/serializers/activation.py
- src/aap_eda/core/utils/credentials.py
- src/aap_eda/wsapi/consumers.py
- tests/integration/api/test_credential_type.py
- tests/integration/wsapi/test_consumer.py
This fix solves the exception when creating a credential_type with injected envs referencing to injected files, and the exception when creating a credential based on such types.
The root cause is that {{ eda.filename.abc }} is not substituable. We need to make this allowable during validation and skip substitution for non extra_vars at credential creation time.
A slight enhancement is not to send files to rulebook via websocket if the file content is empty.
Related to AAP-35595
To test the fix we can create this type and credential:
```
---
fields:
- id: host
label: Kafka Host
help_text: Address of Kafka Host
- id: port
label: Kafka Port
help_text: Kafka Port
- id: topic
label: Kafka Topic
help_text: Kafka Topic
- id: group_id
label: Group ID
help_text: Kafka Group ID
- id: offset
label: …
```
> fix: injected env referencing to injected file

- src/aap_eda/services/activation/engine/podman.py
- src/aap_eda/settings/default.py
- tests/integration/services/activation/engine/test_podman.py
Adds PODMAN_SOCKET_TIMEOUT to the system settings to allow custom timeout for podman socket.
Includes a little refactor of the `get_podman_client` and extends tests.
> feat: enable custom podman socket timeout

- poetry.lock
- pyproject.toml
- src/aap_eda/api/filters/__init__.py
- src/aap_eda/api/filters/rulebook.py
- src/aap_eda/api/views/rulebook.py
- src/aap_eda/settings/default.py
- tests/integration/api/test_rulebook.py
- pin DAB to [2024.12.13](https://github.com/ansible/django-ansible-base/releases/tag/2024.12.13) release tag
- change to using `rest-filters` app from DAB as a default filter backend for filtering and ordering
- add unit test for filtering audit rules by activation instance name
NOTE: Using `rest-filters` changes the keyword `ordering` for sorting to `order` and `order_by`. Also, this change will transfer the freedom to the UI to build the query param with the correct lookup expression, e.g. `/audit-rules/?name__contains=Test`.
JIRA: [AAP-22893](https://issues.redhat.com/browse/AAP-22893)
> feat: [AAP-22893] add filtering by activation instance name to audit rules list view

- src/aap_eda/settings/default.py
app version in openapi spec is hardcoded and outdated
This should be taken dynamically from the package version using the existing "get_eda_version" helper. 
Jira: https://issues.redhat.com/browse/AAP-37834
> fix: use package version for app version in openapi

- src/aap_eda/core/management/commands/create_initial_data.py
Fix the AttributeError raised in `models.utils.get_default_organization()`
```
models.utils.get_default_organization()
AttributeError: module 'aap_eda.core.models' has no attribute 'utils'
```
https://issues.redhat.com/browse/AAP-38148
> fix: [AAP-38148] import utils module properly to solve AttributeError in get_default_organization

- src/aap_eda/api/serializers/activation.py
- src/aap_eda/api/serializers/decision_environment.py
- src/aap_eda/api/serializers/eda_credential.py
- src/aap_eda/api/serializers/event_stream.py
- src/aap_eda/api/serializers/project.py
- src/aap_eda/api/serializers/team.py
- tests/integration/api/test_activation.py
- tests/integration/api/test_decision_environment.py
- tests/integration/api/test_eda_credential.py
- tests/integration/api/test_project.py
- tests/integration/services/activation/test_manager.py
https://issues.redhat.com/browse/AAP-36846
> fix: [AAP-36846] - customize validation error messages

- src/aap_eda/core/exceptions.py
- src/aap_eda/core/utils/credentials.py
- src/aap_eda/wsapi/consumers.py
- tests/integration/wsapi/test_consumer.py
- tests/unit/test_credential_validation.py
https://issues.redhat.com/browse/AAP-38471
> fix: [AAP-38471] - add default values to the user inputs of credentials

- src/aap_eda/api/serializers/activation.py
- src/aap_eda/api/serializers/decision_environment.py
- src/aap_eda/api/serializers/eda_credential.py
- src/aap_eda/api/serializers/event_stream.py
- src/aap_eda/api/serializers/fields/basic_user.py
- src/aap_eda/api/serializers/project.py
Change `created_by` and `modified_by` to the type of `object` in the auto-generated schema file. 
It will solve the failures in https://github.com/ansible/eda-qa/pull/447
https://issues.redhat.com/browse/AAP-34609
> fix: [AAP-34609] - change created_by/modified_by into object type in openapi.json

- tests/integration/services/activation/engine/data/auth.json
- tools/deploy/eda-api/deployment.yaml
- tools/deploy/redis/deployment.yaml
- tools/docker/docker-compose-mac.yml
- tools/docker/nginx/Dockerfile
replace all docker references with gcr mirror
> chore: remove dockerhub images

- src/aap_eda/api/serializers/decision_environment.py
- src/aap_eda/core/validators.py
- tests/integration/api/test_decision_environment.py
This PR adds validation to DE image URLs. 
Upon checking this issue out, we only had validation on registry credentials, and no validation on DE's. 
This PR ensures we have the same validation on both registry credential URLs and Decision environments.
This PR also updates the validation to ensure that if a DE URL with digest is specified, that this is a valid specification.
> [AAP-37476]: Validate DE Urls

- src/aap_eda/api/serializers/activation.py
- src/aap_eda/core/enums.py
- src/aap_eda/core/management/commands/create_initial_data.py
- src/aap_eda/settings/default.py
- tests/integration/api/test_activation_with_event_stream.py
- tests/unit/commands/test_create_initial_data.py
- tools/docker/docker-compose-mac-pg-mtls.yml
- tools/docker/postgres_ssl_config/hba/pg_hba_mtls.conf
- tools/docker/postgres_ssl_config/postgresql-cfg/custom.conf
Create a Postgres credential that can store certificates and keys or userid/password at server startup and attach it to Activations that use EventStream.
This allows us to test mTLS for Postgres, a sample pg_hba file is attached to this PR.
To test this you need to create certificates and keys for
* Postgres Server called (server.crt and server.key)
* EDA Server called (client.crt and client.key)
* You also need to create the CA certificate (ca.crt)
These files have to be present in
tools/docker/postgres_ssl_config/certs
The docker-compose file tools/docker/docker-compose-mac-pg-mtls.yml can be used to test mTLS
The docker-compose file tools/docker/docker-compose-mac.yml can be used to test userid/password auth
https://issues.redhat.com/browse/AAP-38315
> feat: support PG Notify for event streams using credentials

- poetry.lock
- pyproject.toml
This PR will update us to the latest version of podman. 
It does not fix the port issue, but helps us sets us at the latest version of podman, so we can more easily update when we the fix is available.
Jira: https://issues.redhat.com/browse/AAP-38110
Replaces https://github.com/ansible/eda-server/pull/1180/
> chore: upgrade podman dependency - AAP-38110

- src/aap_eda/core/tasking/__init__.py
- src/aap_eda/services/activation/activation_manager.py
- src/aap_eda/services/activation/engine/podman.py
- src/aap_eda/tasks/orchestrator.py
- tests/integration/core/test_tasking.py
- tests/integration/tasks/test_orchestrator.py
The (eda) dispatcher dispatches the start request (chooses the node) and enqueue the manager at the end. The request is processed again in the next loop of the monitor if it takes time and the request can be assigned to another node, then the first time the monitor is executed for the activation, causes the following error:
```
2024-11-22 21:33:49,363 Container args ['ansible-rulebook', '--worker', '--websocket-ssl-verify', 'yes', '--websocket-url', 'wss://f34-h10-000-r640.rdu2.scalelab.redhat.com:443/api/eda/ws/ansible-rulebook', '--websocket-access-token', '******', '--websocket-refresh-token', '******', '--websocket-token-url', 'https://f34-h10-000-r640.rdu2.scalelab.redhat.com:443/api/eda/v1/auth/token/refresh/', '--id', '1388', '--heartbeat', '300']
2024-11-22 21:33:49,464 Container …
```
> fix: prevent race conditions when dispatching start requests - AAP-36642

- poetry.lock
- pyproject.toml
- src/aap_eda/settings/default.py
- tests/integration/api/test_feature_flags.py
- tests/integration/api/test_root.py
- Adds feature-flag API from the django-ansible-base.
- Currently only LIST endpoint is added
API is accessible at - `/api/eda/v1/feature_flags_state/`.
To test, deploy EDA and ensure API is accessible at above endpoint. One can modify the FLAGS variable to see the state reflected at the API endpoint at installtime.
Also satisfies - https://issues.redhat.com/browse/AAP-39595
> [AAP-39136] - Register DAB Feature Flags endpoint

- src/aap_eda/api/serializers/activation.py
- tests/integration/api/test_activation.py
fix AAP-39630.
eda_credentials cannot be null when create or update an activation. empty list [] is allowed.
> fix: eda_credentials field cannot be null

- src/aap_eda/api/serializers/project.py
https://issues.redhat.com/browse/AAP-40152
Remove `created_by` and `modified_by` from the updating payload data. These two fields are updated when they are saved to DB
> fix: [AAP-40152] solve 500 error when project is updated

- src/aap_eda/api/serializers/activation.py
Doing this will exclude edited_at from the required list of the Activation objects in openapi.json
fixes AAP-40348
> fix: Remove edited_at from read_only_fields

- .github/workflows/ci.yaml
Linters are failing with error - 
```
The option "--check" does not exist
```
Removing `--` allows them to function as expect. The `--check` argument still does exist, but the appearance of `--` causes the call to not function as intended.
This failure can be seen in this PR - 
https://github.com/ansible/eda-server/pull/1201
> Fix GH PR Checks

- src/aap_eda/conf/registry.py
- src/aap_eda/tasks/analytics.py
- tests/integration/tasks/test_analytics.py
- tests/unit/test_application_settings.py
AAP-39884 Test and improve code coverage for analytics collection feature
> test: add more tests to analytics settings and scheduling

- tools/docker/docker-compose-mac.yml
This helps improve quality of life for developers to be able to hot reload changes in podman-compose environment, without having to restart the containers.
> chore: mount volumes to docker-compose-mac.yml for hot reloading

- src/aap_eda/settings/default.py
We have detected that ansible-rulebook might be slow at starting when decrypting vaulted variables. 
After https://github.com/ansible/eda-server/pull/1088 we have received several reports for activations being restarted as unresponsive after not receive the heartbeat in time. In combination with https://github.com/ansible/ansible-rulebook/pull/733 we agreed to increase the default value of RULEBOOK_READINESS_TIMEOUT_SECONDS for safeness. 
Jira: https://issues.redhat.com/browse/AAP-40490
Create an activation with multiple credentials. 
None
The activation is not set as unresponsive and it is set as running by the system
None
None
> fix: increase activation readiness timeout AAP-40490

- poetry.lock
- pyproject.toml
- src/aap_eda/services/activation/engine/podman.py
- tests/integration/services/activation/engine/test_podman.py
**Will be timing the merge of this PR with PDE**
- What is being changed?
Updates podman dependancy to 5.4.0.1, where the upstream fix is available to ensure custom ports can be used with tags and are respected.
- Why is this change needed?
To ensure containerized/RPM installers can use custom ports for decision environments.
- How does this change address the issue?
The fix was merged in the upstream. This PR updates our podman dependency to 5.4.0.1 where the fix is available.
Closes #XXX (if applicable)
Jira: [AAP-38110](https://issues.redhat.com/browse/AAP-38110) (if applicable)
1. Run locally using docker-compose
2. Validate a rulebook can be run using an image like - 
```
registry.redhat.io:443/ansible-automation-platform-25/de-supported-rhel9:latest
```
Both the port, and the tag …
> AAP-38110 - Respect custom ports for authentication (Update Podman Dependancy)

- src/aap_eda/settings/default.py
- src/aap_eda/settings/post_load.py
- tests/integration/api/test_feature_flags.py
- tests/unit/data/demo_settings.yaml
- tests/unit/test_import_settings.py
env EDA_MODE was not set. All settings from production/development/testing are imported.
This fix sets EDA_MODE to production by default to avoid conflict settings from different modes. Different mode can still be set by the env var.
Also directly call toggle_feature_flags function from DAB.
[AAP-41917](https://issues.redhat.com/browse/AAP-41917)
For testing pick a setting and set to different value in /etc/eda/settings.yaml under production/development/testing sections and prove the value is selected according to explicitly set EDA_MODE. When EDA_MODE is not set, the value under production is selected.
> [AAP-41917] fix: default EDA_MODE to production

- src/aap_eda/settings/defaults.py
AAP-42126
WEBSOCKET_SSL_VERIFY and CONTROLLER_SSL_VERIFY in defaults.py were set to str type because they can be strings like "yes" or "no". But a value of true or false fails the type validation, preventing the server from starting up.
[AAP-42126](https://issues.redhat.com/browse/AAP-42126)
The fix changes the type from `str` to `Union[bool, str]`. The eda-server has code to convert `yes` or `no` to a bool. When they are sent to ansible-rulebook, they become `"True"` or `"False"` which are valid and expected.
Different inputs (`true`, `yes`, `True`) have been tested and proved working in activation.
> fix: WEBSOCKET_SSL_VERIFY and CONTROLLER_SSL_VERIFY to be a bool type

- src/aap_eda/api/serializers/activation.py
- src/aap_eda/api/views/activation.py
- tests/integration/api/test_activation.py
Fix an internal 500 error when calling api to update an activation on k8s
[AAP-42437](https://issues.redhat.com/browse/AAP-42437)
If no new name or k8s_service_name is provided when request updating the activation, the values from the existing activation are pulled. They are needed for validation. 
In addition, when the k8s_service_name is cleared through the update request, it will be regenerated with the default value.
To test the fix
1. Update an activation without changing name on k8s, it no longer raises a 500 internal error.
2. Create an activation with a customized k8s_service_name and clear it through an update, verify the activation's k8s_service_name is assigned to a default value generated based on the activation name.
> fix: process k8s_service_name during activation update

- tools/docker/docker-compose-dev.yaml
The purpose of this PR is to set multiple default workers and default activation workers per node to simulate the scenario that we will have in OCP with multiple main processes of dispatcher listening in the same channel. 
I don't use `replicas` of the compose spec because it has some limitations, like for example the capability of opening a port, so it is better a little copy-paste of the number of desired services. 
Jira: https://issues.redhat.com/browse/AAP-42483
> chore: update docker-compose-dev to set multiple workers AAP-42483

- src/aap_eda/settings/defaults.py
podman settings are optional. The startup should not fail if the installer explicitly set them to null.
[AAP-42671](https://issues.redhat.com/browse/AAP-42671)
> fix: podman settings are optional

- src/aap_eda/services/activation/engine/podman.py
- tests/integration/services/activation/engine/test_podman.py
We were creating the container with "remove=True". This was due to the first design where we had a worker attached to the container and we relied on podman to get deleted the container once it is stopped. We found that this parameter did not work properly in the podman client, so we added a cleanup logic anyway. After the refactor of activations, this was never needed, since we fetch the logs in the monitor after stop the container, before remove it. 
Now after the upgrade of the podman client, this [has been fixed ](https://github.com/containers/podman-py/pull/435)and the container is actually removed when it is stopped. Our cleanup logic run under a conditional "if container.exists()" so we can incur in race conditions since there is a time window between podman stops the container and …
> fix: cleanup podman containers and handle not found exceptions AAP-42708

- src/aap_eda/api/serializers/activation.py
- src/aap_eda/api/views/activation.py
- tests/integration/api/test_activation_with_credential.py
- tests/integration/api/test_activation_with_event_stream.py
Rework how to update credentials and extra_vars in an activation
[AAP-42639](https://issues.redhat.com/browse/AAP-42639)
If an activation contains credentials that have extra_vars injector in their type schemas, for example, the credential automatically attached when an event_stream is used, the code will automatically insert extra vars to the activation's extra_var field. When such credentials are added/removed/updated in the activation, the corresponding extra_var is not updated properly.
To fix the problem we now restore the extra_var to its origin before credential insertion. Then re-insert additional extra vars to this attribute one by one iterating through new credentials in the activation. In order to work properly for all possible updates, we pull all required attributes from the …
> fix: update credentials in an activation

- src/aap_eda/core/management/commands/create_initial_data.py
- tests/integration/wsapi/test_consumer.py
Adds AAP injectors, following up on the collection update. Enables them as extra_vars, and as environment variables
Duplicate of: https://github.com/ansible/eda-server/pull/1162 with updated env var values.
EDAQA Tests are fixed by: https://github.com/ansible/eda-qa/pull/465
e2e test run - https://github.com/ansible/eda-server/actions/runs/14172609841
> Add AAP Injectors

- src/aap_eda/services/activation/activation_manager.py
- src/aap_eda/services/activation/tee_system_logger.py
- src/aap_eda/settings/post_load.py
- tests/conftest.py
- tests/integration/services/activation/test_tee_system_logger.py
Add logging functionality to show in activation worker logs as well as the rulebook process logs.
https://issues.redhat.com/browse/AAP-41782
> implement tee-system-logger AAP-41782

- src/aap_eda/api/views/activation.py
- src/aap_eda/middleware/request_log_middleware.py
- src/aap_eda/settings/post_load.py
- src/aap_eda/wsapi/consumers.py
- tests/integration/api/test_activation.py
- tests/unit/test_request_log_middleware.py
Request ID should have a default value when there is no Gateway.
https://issues.redhat.com/browse/AAP-42756
> [AAP-42756] fix: Generate default request id when it's not available

- src/aap_eda/settings/core.py
- tests/integration/api/test_feature_flags.py
Add new feature flag setting for the future development of the dispatcher as new background tasking system. 
Also refactor redundant test. 
Jira: https://issues.redhat.com/browse/AAP-43148
> feat: add dispatcherd feature flag setting AAP-43148

- src/aap_eda/core/management/commands/rqworker.py
- src/aap_eda/core/management/commands/scheduler.py
- src/aap_eda/settings/core.py
- tests/unit/commands/test_rq_cmd_wrapper.py
Wrap rq workers commands to switch between the existing rq workers or the future dispatcherd based on the feature flag. 
depends on https://github.com/ansible/eda-server/pull/1257
Jira: https://issues.redhat.com/browse/AAP-43102
> feat(dispatcherd): Add rq command wrapper AAP-43102

- src/aap_eda/services/auth.py
Formally, this is a problem for the dev environment right now, so don't panic. See:
```
Traceback (most recent call last):
File "/app/src/src/aap_eda/services/activation/activation_manager.py", line 213, in _start_activation_instance
container_request = self._get_container_request()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/src/src/aap_eda/services/activation/activation_manager.py", line 1033, in _get_container_request
return self.db_instance.get_container_request()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/src/src/aap_eda/services/activation/engine/common.py", line 168, in get_container_request
cmdline=self._build_cmdline(),
^^^^^^^^^^^^^^^^^^^^^
File "/app/src/src/aap_eda/services/activation/engine/common.py", line 189, in _build_cmdline
access_token, refresh_token = …
```
> Only create websocket account locally

- src/aap_eda/api/event_stream_authentication.py
- src/aap_eda/core/tasking/__init__.py
- src/aap_eda/core/utils/rulebook.py
- src/aap_eda/services/activation/activation_manager.py
- src/aap_eda/services/activation/engine/kubernetes.py
- src/aap_eda/services/activation/engine/podman.py
- src/aap_eda/services/activation/restart_helper.py
- src/aap_eda/services/project/imports.py
- src/aap_eda/tasks/orchestrator.py
- src/aap_eda/utils/__init__.py
- src/aap_eda/wsapi/consumers.py
- tests/integration/services/activation/test_manager.py
- tests/integration/services/test_project_import.py
- tests/integration/wsapi/test_consumer.py
- tests/unit/test_utils.py
Aligning logger levels in the backend to match our definitions in [AAP-41838](https://issues.redhat.com/browse/AAP-41838). An outline of the agreed definitions:
**Debug:** Detailed information for developers, useful for debugging.
**Info:** General operational messages that indicate normal progress of the application.
**Warning:** Something unexpected happened, but the application can recover and continue running.
**Error:** A failure occurred that prevents some part of the application from functioning correctly, but the system is still running.
We currently do not use "Critical" anywhere in the backend logs. 
I have also included some minor cosmetic changes to the log messages. More changes could have been done to align our messages across the board, but this would have resulted in scope …
> chore: align backend log levels

- src/aap_eda/api/serializers/activation.py
- tests/integration/api/test_activation_with_event_stream.py
When the even streams are removed from an activation, the UI sends "[]\n" to the backend which were interpreted non-empty thus the event stream credential was mistakenly added.
[AAP-43604](https://issues.redhat.com/browse/AAP-43604)
Parse the source_mapping string and accurately determine whether there are source mapping or empty. Only inject the extra_vars when there are true source mappings.
> [AAP-43604] fix: properly detect whether source_mappings are empty

- tests/integration/core/test_tasking.py
- tests/unit/test_settings.py
This PR changes tests to dynamically retrieve `REDIS_HOST` from settings in order to fix failures in case `REDIS_HOST` might be defined differently.
> chore: update tests to retrieve host var from settings

- src/aap_eda/services/activation/activation_manager.py
The error status and status_message were rolled back by the transaction manager. User cannot get the true error.
[AAP-43866](https://issues.redhat.com/browse/AAP-43866)
Remove `@run_with_lock` for `_check_start_prerequirements` otherwise the error raised by https://github.com/ansible/eda-server/blob/main/src/aap_eda/services/activation/activation_manager.py#L143 will roll back the status change in one line above.
> [AAP-43866] fix: do not wrap with run_with_lock for _check_start_prerequirements

- src/aap_eda/settings/core.py
- src/aap_eda/tasks/analytics.py
- src/aap_eda/tasks/orchestrator.py
- src/aap_eda/tasks/project.py
- src/aap_eda/wsapi/consumers.py
- tests/integration/tasks/test_analytics.py
- tests/integration/tasks/test_orchestrator.py
- tests/integration/test_advisory_lock.py
- tests/integration/utils.py
- tests/integration/wsapi/test_consumer.py
- tests/unit/test_orchestrator.py
For the PoC of dispatcherd we used [pg advisory_locks](https://www.postgresql.org/docs/current/explicit-locking.html#ADVISORY-LOCKS) to ensure job uniqueness. It will be part of the final implementation. It has been so far a robust and simpler way to ensure uniqueness in comparison to existing `unique_enqueue` helper, which would not have a replacement. 
Since the use of the advisory lock is not tied to dispatcherd, this PR explores its use as well for the current implementation with RQ redis, assuming that will simplify the later implementation under a feature flag of the dispatcherd itself. 
There is no functional change and everything should work transparently. I have been testing it extensively and tomorrow will do more battery of tests, I have confidence. I leave the open the draft …
> feat(dispatcherd): add advisory lock for task uniqueness

- tools/docker/Dockerfile
In light of upcoming changes in ansible-core, pinning the version to 2.16 while we investigate the impact.
[AAP-43723](https://issues.redhat.com/browse/AAP-43723)
https://github.com/ansible/ansible/pull/84621
> chore: pin ansible-core in Dockerfile

- src/aap_eda/analytics/utils.py
- tests/integration/analytics/test_package.py
https://issues.redhat.com/browse/AAP-44575
Ignore AUTOMATION_ANALYTICS_URL from the application settings set by the Gateway.
> fix: [AAP-44575] Always use AUTOMATION_ANALYTICS_URL from EDA settings

- .github/workflows/e2e-dispatch.yml
- src/aap_eda/api/serializers/activation.py
- src/aap_eda/core/utils/k8s_service_name.py
- tests/integration/api/test_k8s_activation.py
- tests/unit/test_k8s_service_name.py
Enhance `create_k8s_service_name(activation_nam)` to accept any activation name
[AAP-43742](https://issues.redhat.com/browse/AAP-43742)
For k8s deployment we always prepare a service name in case it is needed for the rulebook. The current implementation of `create_k8s_service_name(activation_nam)` converts some non rfc_1035 compliant letters such as dot and _ into -, but rejects other non-qualified letters. This prevents the users from creating activation with a name containing such letters even if the service is not eventually needed.
The solution is to always create a rfc_1035_compliant service name. Never reject an activation name. Activation name is used only as a reference to create the service name. No special requirements should be imposed.
> [AAP-43742] fix: auto generate service name. Do not throw error

- src/aap_eda/core/views.py
- tests/integration/core/test_views.py
Change the response from `/v1/status/` endpoint to use enum provided by DAB.
JIRA: [AAP-43898](https://issues.redhat.com/browse/AAP-43898)
> fix: [AAP-43898] update status endpoint response to DAB enum

- src/aap_eda/api/constants.py
The error "Rulebook has changed since the sources were mapped. Please reattach event streams" is caused by validating field source_mappings.
[AAP-44583](https://issues.redhat.com/browse/AAP-44583)
This fix changes the validate error message of the 404 error body from key rulebook to source_mappings. The key must match the actual field in the creation/update body so that the UI can correctly highlight the field for user to fix error.
> fix: change error field from rulebook to source_mappings

- src/aap_eda/analytics/utils.py
- src/aap_eda/api/views/eda_credential.py
- src/aap_eda/tasks/analytics.py
- tests/integration/analytics/test_utils.py
- tests/integration/api/test_eda_credential.py
- tests/integration/tasks/test_analytics.py
When the gather interval in the analytics credential changes, before the fix eda-server will wait until the scheduled analytics based on the old interval is executed, and then schedule the next job with the new interval. The fix immediately cancels the scheduled job and reschedules the next job to run at the new interval
[AAP-44570](https://issues.redhat.com/browse/AAP-44570)
> fix: reschedule analytics when interval changes in credential

- tools/docker/docker-compose-dev.yaml
The use of replicas has some inconveniences and limitations. It does not allow to map ports if we need. It is not always compatible with other consumers of our compose file. This has been particularly relevant for the development of the integration with dispatcherd. This can be also considered one of the PR's part of the integration/onboarding of dispatcherd. 
This PR removes the replicas config and creates a second instance of the workers. This to make sure we develop and test against scenarios of redundancy where other race conditions can happen. It is necessary for dispatcherd but also valuable in general (which is why the default value of the replicas was 2)
> chore: remove replicas for docker-compose-dev

- src/aap_eda/tasks/orchestrator.py
- tests/integration/tasks/test_orchestrator.py
Minor refactor around the function `dispatch` this is to avoid confusion with dispatcherd.
> refactor: rename dispatch to queue_dispatch

- .github/workflows/e2e-dispatch.yml
Add a new param to set the dispatcherd feature flag in our e2e-dispatch workflow. 
This workflow is always executed from main. This allows us to run on demand the test suite with the feature flag enabled. Once the feature flag is implemented and merged in main, we will have to update this workflow to add a matrix strategy and run the test suite by default with the flag enabled. For now, it is intended to work only for on-demand runs.
> ci: add param for dispatcherd flag in e2e-dispatch

- src/aap_eda/analytics/collector.py
- src/aap_eda/core/management/commands/create_initial_data.py
- src/aap_eda/core/management/commands/gather_analytics.py
- src/aap_eda/core/management/commands/rqworker.py
- src/aap_eda/core/management/commands/scheduler.py
- src/aap_eda/settings/core.py
- src/aap_eda/settings/features.py
- src/aap_eda/tasks/analytics.py
- tests/integration/analytics/test_collector.py
- tests/integration/analytics/test_gather_analytics.py
- tests/integration/api/test_feature_flags.py
- tests/integration/tasks/test_analytics.py
- tests/unit/commands/test_rq_cmd_wrapper.py
- tests/unit/test_features.py
Get whether a feature flag is on or off as a constant from the new features module.
It improves the code readability and slightly the performance as the flags are now cached.
This work is to prepare the merging of the dispatcherd feature which is guarded by a flag.
> refactor: get feature flags from features module

- src/aap_eda/core/models/event_stream.py
- src/aap_eda/utils/__init__.py
- tests/unit/test_utils.py
For dispatcherd we need to sanitize the channel name as we already do for event streams. There is no need to fill the code with `.replace()` calls. 
Instead create a helper that can sanitize the name in a more reusable and reliable way.
> chore: add helper to sanitize pg identifiers

- src/aap_eda/api/views/activation.py
- tests/integration/api/test_activation.py
Objectives for this bug [https://issues.redhat.com/browse/AAP-40077]:
- Update restart API endpoint such that, when a user attempts to restart, we detect if the deployment type is 'podman' and the 'activation-worker-node' is offline, we should block the restart and return an error warning the user that a running container will be orphaned.
- Enhance restart API endpoint with a force option where, if enabled, the restart will go through.
Activation containers are being left behind (orphaned) on nodes that go offline in an multi-node deployment. 
The user has no way of knowing they they are leaving behind these orphaned containers.
> Bug/remove container-aap 40077

- src/aap_eda/tasks/project.py
- tests/integration/test_advisory_lock.py
Update job uniqueness tests to mock proxy functions. 
Also moves import/sync project tasks from the job decorator to the direct calling, this for consistency and convenience at testing.
(projects jobs continue working as expected, manually verified)
> test: fix job uniqueness test

- pytest.ini
Define which is the expected test paths for pytest. If you configure your working project to work with local versions of libraries, like ansible_base or dispatcherd, by default pytest will lookup tests also from those projects and potentially ending up in errors. With this setting we explicitly set where are the tests that pytest will run for this project.
> chore: define pytest test paths

- tools/ansible/eda_init.yml
Add to eda_init.yml playbook tool the capability to also create sample activations, disabled by default. Useful for testing and demos.
> chore: extend eda_init playbook tool

- src/aap_eda/api/serializers/project.py
- src/aap_eda/api/views/project.py
- tests/integration/api/test_project.py
The URL attribute in the project is allowed to be set in the body to patch a project.
ATF tests are added to change the URL of an existing project 
https://issues.redhat.com/browse/AAP-41454
> AAP-41454 - [API] Make project scm_url editable in the patch API

- src/aap_eda/services/activation/engine/kubernetes.py
- tests/integration/services/activation/engine/test_kubernetes.py
https://issues.redhat.com/browse/AAP-45298
Rework [PR](https://github.com/ansible/eda-server/pull/1264) to solve the timeout issue when disabling/deleting activations.
The output on the UI page after being disabled:
> fix: [AAP-45298] Stuck in disabling/deleting an activation in ocp env

- src/aap_eda/data/playbooks/project_clone.yml
`omit` should always be the end state, and not used in the middle. 
https://issues.redhat.com/browse/AAP-46553
e.g
```
version: "{{ scm_branch | default(omit) | quote }}"
```
gets interpreted as 
```
"cmd": "/usr/bin/git checkout --force '<<Omit>>'",
```
> fix: [AAP-46553] modify the project clone playbook for ansible-core 2.19

- src/aap_eda/api/serializers/activation.py
- tests/integration/api/test_activation.py
The log_tracking_id is missing in the copied activation.
https://issues.redhat.com/browse/AAP-46785
> fix: [AAP-46785] set log_tracking_id when copying activations

- src/aap_eda/core/exceptions.py
- src/aap_eda/core/management/commands/scheduler.py
- tests/unit/commands/test_rq_cmd_wrapper.py
This PR changes the approach to handle the dispatcherd flag in the scheduler. Instead or returning an error and creating noise for users, that also need to modify their deployments to not deploy the scheduler which would be restarting all the time in default deployments,  it applies a less disruptive approach by just warning about it and running a noop loop.
> fix: Run noop loop in scheduler under dispatcherd flag

- src/aap_eda/api/serializers/project.py
- src/aap_eda/core/validators.py
- src/aap_eda/services/project/scm.py
- tests/integration/api/test_project.py
- tests/unit/test_scm.py
Now validate project url, branch, and refspec
https://issues.redhat.com/browse/AAP-47166
> fix: add more validations to project attributes

- tests/unit/test_application_settings.py
Attempt to fix test_read_remote_setting that fails sporadically.
> fix: patch rather than sleep for time sensitive pytest

- src/aap_eda/api/views/project.py
- tests/integration/api/test_project.py
This commit causes auto sync/import of a project when one of its url, scm_branch, or scm_refspec is updated,
without the user having to manually trigger the sync via the UI/API.
https://issues.redhat.com/browse/AAP-46254
> feat: [AAP-46254] trigger project resync after project update

- src/aap_eda/core/management/commands/create_initial_data.py
- tests/integration/core/test_create_initial_data.py
A user belongs to a team with organization-level admin role cannot see the organization from the list organizations api endpoint. Comparing the Organzation Project Admin in Controller, it has `view_organization`
The `view_organization` permission is missing for EDA organization Project Admin in EDA 
https://issues.redhat.com/browse/AAP-48587
This PR adds `view_organization` permission to any organization-level admin role
The fix has been tested with aap-dev deployment. An ATF test should be added for automation after the fix is merged.
> fix: add view_organization permission to organization-level admin rules

- src/aap_eda/settings/core.py
- src/aap_eda/tasks/orchestrator.py
In some scenarios with high concurrent workload I have observed intermittent healthcheck failures. This PR's increases the default timeout with a more safe value (default is 1)  and exposes it as setting. Depending on the setup this value might need to be adjusted but scaling up workers or adjusting subprocesses per worker should be the right approach in the most of the cases.
> chore(dispatcherd): parameterize and increase queue healthcheck timeout

- poetry.lock
The current pinned release does not build with more recent versions of setuptools, and 3.1.0 removes the problematic code.
> chore: update python-daemon version to a newer one

- src/aap_eda/core/validators.py
- src/aap_eda/services/project/scm.py
- tests/unit/test_scm.py
- tests/unit/test_validators.py
Attempt to fix the URL validation error when it contains %20.
https://issues.redhat.com/browse/AAP-50582
Enhance the validation utilizing urllib.parse.urlparse where possible. Added a lot of more test cases.
Look at test_scm.py test_is_git_url_valid() for various valid and invalid URLs.
> fix: enhance git url validation

- src/aap_eda/core/management/commands/fix_project_state.py
- src/aap_eda/tasks/project.py
- tests/integration/tasks/test_projects.py
- tests/unit/commands/test_fix_project_state.py
Fix bug in existing monitor_project_tasks for pending state. 
Add new logic to handle running state. 
Add new django command to manually change the import state of a project
https://issues.redhat.com/browse/AAP-51139
Fix the bug in requeueing pending projects that are no longer in the queue.
Detect running projects that are no longer in the queue or already failed but not updated in database.
The django command can be used as a last resort helping the project to move out of a stuck state.
Once a project is stuck in pending or running, it cannot be restarted. This work helps to move such projects out of the situation.
> fix: moving project out of stuck pending or running state

- src/aap_eda/api/serializers/credential_type.py
- src/aap_eda/api/serializers/eda_credential.py
- src/aap_eda/core/validators.py
- tests/integration/api/test_eda_credential.py
The test function for eda_credential was broken, it needs to support some of the Credential Types that have optional metadata fields like GitHub App Installation Access Token Lookup We need to support empty metadata during the test. If the metadata is empty we have to look at the credentials schema and see if it has mandatory fields and then raise an error. If the fields are optional then we should allow empty metadata
https://issues.redhat.com/browse/AAP-52232
> fix: the test function was broken for eda_credential

- src/aap_eda/settings/defaults.py
- src/aap_eda/settings/post_load.py
- tests/unit/test_settings.py
Support extended set of boolean values (true/false/yes/no/1/0) for MQ_TLS setting.
Currently if a non-standard boolean value is used (yes/no/1/0), this can cause issues during an upgrade.
[AAP-52587](https://issues.redhat.com/browse/AAP-52587)
Generated with assistance from Cursor (claude-4-sonnet).
> AAP-52587: support extended boolean values

- src/aap_eda/api/views/external_event_stream.py
- tests/integration/api/test_event_stream_token.py
To include all headers you have to explicitly set the
additional_data_headers = *
* If the header key is used for Authentication it will be redacted
* To pick and choose which headers get included, list them as a comma delimited string in additional_data_headers e.g Host,Origin,X-Request-ID
* Any header that starts with X-Envoy will be dropped
* X-Trusted-Proxy,X-Forwarded-For,X-Real-IP will be dropped
> fix: handling of HTTP headers in EventStreams

- tests/integration/api/test_vault.py
Failure documented in:
https://github.com/ansible/django-ansible-base/pull/852
I expect that DAB is seeing `test_failed_decrypt` fail because of minor differences in behavior due to versions of dependencies. The failure seems to occur due to minor and inconsequential differences in the exact syntax of the error message observed. This change generalizes the expected regex for the exception's text.
> Fix downstream failure from DAB
