ansible/eda-server

src/aap_eda/api/serializers/project.py
src/aap_eda/api/views/project.py
tests/integration/api/test_project.py

- Add validators to Project update serializer to return more clear and concise error output
Solves: [AAP-14636](https://issues.redhat.com/browse/AAP-14636)

[AAP-14656] Improve Project Update error output

---

src/aap_eda/api/views/project.py

- Fix response and request schema
- Update description
Jira: https://issues.redhat.com/browse/AAP-14775

Fix openapi schema for project sync

---

src/aap_eda/settings/default.py

Solves [AAP-14982](https://issues.redhat.com/browse/AAP-14982)

[AAP-14982] Set default_timeout to -1 (no timeout) on queue class

---

src/aap_eda/core/migrations/0005_auto_20230810_1329.py

After adding `status` to Activation, we have to populate them with the original data, rather than the default `pending`

Fix migration to keep old activations status

---

src/aap_eda/services/ruleset/activate_rulesets.py
tests/integration/services/test_ruleset_activate.py

* fix rules_count and rules_fired fields getting reset to 0 on Activation completion

[AAP-15063] Fix Number of Rules and Fired Count getting reset

---

src/aap_eda/services/ruleset/activate_rulesets.py

Follow up  #316 
Refactor: extract common code into a function. Reduce the number of DB saves where possible.

Update statues of activation and instance together

---

src/aap_eda/api/filters/__init__.py
src/aap_eda/api/filters/activation.py
src/aap_eda/api/views/activation.py
tests/integration/api/test_activation_instance.py

* Remove unused filters from activation instance logs
* Add 'log' filtering for activation instance logs

[AAP-13350] Update filtering for Activation Instance Logs

---

tools/deploy/eda-ui/deployment.yaml
tools/deploy/kustomization.yaml

For the changes on eda-ui (https://github.com/ansible/ansible-ui/pull/766), this PR add new environment variables `EDA_PROTOCOL` and `EDA_HOST` to `eda-ui` container.
Related to: https://github.com/ansible/eda-server/pull/359

chore: fix deployment script for changes in eda-ui image

---

tools/deploy/eda-api/deployment.yaml

This is a follow-up for https://github.com/ansible/eda-server/pull/348

Correct service account name

---

src/aap_eda/api/views/activation.py
src/aap_eda/services/ruleset/activate_rulesets.py
src/aap_eda/tasks/__init__.py
src/aap_eda/tasks/ruleset.py
tests/integration/api/test_activation.py
tests/integration/tasks/test_ruleset.py

Sovles: [AAP-15287](https://issues.redhat.com/browse/AAP-15287)

[AAP-15287] Add transaction atomic to solve race conditions when restarting activation

---

tools/docker/docker-compose-dev.yaml
tools/docker/docker-compose-stage.yaml

Version 4.5 is no longer available.

chore: update EDA_PODMAN_VERSION default to use only major version

---

src/aap_eda/api/views/activation.py
src/aap_eda/api/views/decision_environment.py

Makes ActivationInstanceViewSet and DecisionEnvironmentViewSet consistent with other view sets in setting rbac_resource_type from ResourceType.

Set rbac_resource_type using ResourceType.

---

src/aap_eda/tasks/ruleset.py
tests/integration/tasks/test_ruleset.py

Set current_job_id for activations started by scheduler

---

.github/workflows/ci.yaml
.gitignore
poetry.lock
pyproject.toml

Add test coverage and update CI pipelines to upload the report to [codecov](https://about.codecov.io/). 
You can test it locally:
```
pytest -vv --cov=./ --cov-report=xml
xdg-open htmlcov/index.html  # On Linux
open htmlcov/index.html     # On macOS
```
Jira: https://issues.redhat.com/browse/AAP-15759

test: add test coverage - AAP-15759

---

src/aap_eda/services/ruleset/activate_rulesets.py
src/aap_eda/services/ruleset/activation_kubernetes.py
src/aap_eda/services/ruleset/activation_podman.py

Follow up recent PRs with a few minor enhancements and bug fixes, center around saving activation and instances:
1. Replace `filter().update()` with `save(update_fields=)`. This way modified attributes remain in the in memory objects.
2. Call `refresh_from_db()` after a long running activation instance
3. Populate `status_update_at` when an activation is saved
4. Replace `except (IntegrityError, DatabaseError)` with `except DatabaseError`

Ensure saved activation and instance attributes are accurate

---

poetry.lock

CVE: https://nvd.nist.gov/vuln/detail/CVE-2023-32681
Jira: https://issues.redhat.com/browse/AAP-14999

chore: upgrade requests library - AAP-14999

---

src/aap_eda/api/views/activation.py
tests/integration/api/test_activation.py

Solves: [AAP-16305](https://issues.redhat.com/browse/AAP-16305)

[AAP-16305] Fix the enabling activation when its status is pending

---

src/aap_eda/api/filters/__init__.py
src/aap_eda/api/filters/role.py
src/aap_eda/api/views/auth.py
tests/integration/api/test_auth.py

Implements https://issues.redhat.com/browse/AAPRFE-885

Allow filtering on roles api endpoint

---

src/aap_eda/api/filters/activation.py
src/aap_eda/api/views/decision_environment.py
tests/integration/api/test_activation.py
tests/integration/api/test_decision_environment.py

* add a check for activations using DE on delete
* add force flag to force delete DE
* add filter by decision_environment_id for list Activations
Solves: [AAP-14680](https://issues.redhat.com/browse/AAP-14680)

[AAP-14680] Add check for DE deletion if in use by Activations 

---

src/aap_eda/api/exceptions.py
src/aap_eda/api/views/activation.py
src/aap_eda/api/views/decision_environment.py
tests/integration/api/test_decision_environment.py

Follow up for https://github.com/ansible/eda-server/pull/402

chore: Fix warning message exception type for DE

---

src/aap_eda/api/filters/activation.py
src/aap_eda/api/views/credential.py
tests/integration/api/test_activation.py
tests/integration/api/test_credential.py

- Filter activations by credential id
- New force flag at delete credentials, prevent deletion of dependent credentials without flag. 
Jira: https://issues.redhat.com/browse/AAP-16610

feat: aap-16610 handle deletion of dependent credentials

---

.editorconfig

Taken from ansible-rulebook.  Added specific markdown settings.

(chore): Add .editorconfig file.

---

src/aap_eda/wsapi/consumers.py

As discussed in our dev sync, there is no need to update activation status when receiving heartbeats.

No need to update status when receiving heartbeats

---

tools/docker/docker-compose-dev.yaml
tools/docker/docker-compose-stage.yaml

Hotfix for https://github.com/ansible/eda-server/pull/437

fix(ci): remove port binding in docker-compose

---

src/aap_eda/tasks/activation_request_queue.py
tests/integration/tasks/test_activation_request_queue.py

If multiple requests have been queued for an activation we don't have to execute them one by one. The arbitrate logic consolidates them base on the sequence only, regardless of the current status of the activation. Many of the consolidations may not actually happen because the view already has validation based on the current status. Furthermore the manager has validations too before the request is actually executed.

Arbitrate queued activation requests

---

src/aap_eda/services/activation/engine/kubernetes.py

Fixed the duplicate db logs caused by the timestamp conversion.

Refactor: remove duplicate db logs in k8s

---

src/aap_eda/settings/default.py

Add module name to logging format.

chore: add module name to logging format

---

src/aap_eda/services/activation/engine/podman.py
src/aap_eda/services/activation/manager.py

Better handling of exceptions and fix some flows when the activation status was not updated properly.

refactor: improve handling exception at start method

---

src/aap_eda/tasks/orchestrator.py

there was a bug and the job is not purged if the task fails. Also improves readability for the queue and adds docstrings

refactor: improve orchestrator: dosctrings, exception handling

---

src/aap_eda/services/activation/engine/podman.py

Now the error logs are shown on the details page like:
```
2023-11-10 14:21:02,678 - ansible_rulebook.engine - INFO - load source
2023-11-10 14:21:02,908 - ansible_rulebook.engine - ERROR - Source error Could not find source plugin for ansible.eda.pg_listener
2023-11-10 14:21:02,908 - ansible_rulebook.engine - ERROR - Shutting down source: ansible.eda.pg_listener error : Could not find source plugin for ansible.eda.pg_listener
2023-11-10 14:21:02,908 - ansible_rulebook.engine - INFO - Broadcast shutdown to all source plugins
```
Resolves: [AAP-18150](https://issues.redhat.com/browse/AAP-18150)

refactor: turn on stderr to capture podman error logs

---

src/aap_eda/services/activation/manager.py
src/aap_eda/tasks/orchestrator.py

also Include restart count in user log

Set initial status to pending at restart

---

tools/docker/docker-compose-dev.yaml
tools/docker/docker-compose-mac.yml
tools/docker/docker-compose-stage.yaml

Added additional env vars in docker-compose to set
* env vars
* log_level for ansible-rulebook
* container name prefix in rework activation branch (coming soon)

chore: added additional env vars in docker-compose

---

src/aap_eda/services/activation/manager.py

- Set the "stopping" status at the right places
- Ensure cleanup is performed in completed and failed workflows.

fix: ensure cleanup stage in every flow

---

src/aap_eda/services/activation/manager.py
src/aap_eda/settings/default.py
src/aap_eda/tasks/orchestrator.py
tools/deploy/eda-activation-worker/deployment.yaml
tools/deploy/eda-api/deployment.yaml
tools/deploy/eda-default-worker/deployment.yaml
tools/deploy/eda-scheduler/deployment.yaml

- set a timeout for RQ Queues
- ensure activation is deleted when errors occurs
- fix an error running cleanup for activations without instance or pod
id
- fix flow for failed instance by image pull error.

refactor: fix some issues regarding activations

---

src/aap_eda/services/activation/engine/kubernetes.py

k8s should not handle exit code != 0 at starting the activation. If the pod has an exit code it means it was executed, so their state should be handled by the monitor, which knows how to apply the restart policy. `_wait_for_pod_to_start` should check only that the pod has been started, but not perform operations of its status after start. 
Otherwise, the manager treat it as error instead of failed:

refactor: remove handling error at start in k8s

---

tests/integration/api/test_activation.py
tests/integration/services/activation/engine/test_kubernetes.py
tests/integration/services/activation/engine/test_podman.py
tests/integration/tasks/test_orchestrator.py

Fix or update existing tests to pass everything.

test: update existing tests

---

.github/workflows/ci.yaml
poetry.lock
pyproject.toml
src/aap_eda/api/urls.py
src/aap_eda/core/authenticator_plugins/ldap.py
src/aap_eda/settings/default.py
tools/docker/Dockerfile

This PR adds experimental code to integrate django-ansible-base with EDA.
_NOTE:_ It might get removed later down the road.

Experimental django-ansible-base integration (might be removed later)

---

docs/development.md
tests/integration/api/test_authenticators.py

* Add notes development docs for LDAP Integration dependencies 
* Add minimal tests for LDAP Integration

Add docs and tests for experimental LDAP Integration

---

src/aap_eda/api/serializers/project.py
src/aap_eda/core/validators.py
src/aap_eda/services/activation/manager.py
tests/integration/api/test_extra_var.py

* Add validation for extra var on create
Solves: [AAP-18358](https://issues.redhat.com/browse/AAP-18358)

[AAP-18358] Add key/value pair validation for extra var

---

src/aap_eda/api/views/source.py
src/aap_eda/settings/default.py
tests/integration/api/test_source.py

converted to use underscore for channel names
The dsn name should have spaces and not commas

pg notify channel names can't have dashes

---

poetry.lock
pyproject.toml
src/aap_eda/settings/default.py

* define ansible base features to be used
* import ansible base dynamic settings
* revert to using latest from devel branch of django-ansible-base

fix: add dynamic settings from django-ansible-base & revert to use latest devel branch

---

poetry.lock
src/aap_eda/settings/default.py

This PR adds changes to enable JWT authentication in EDA from django-ansible-base.

[AAP-19306] Add DAB JWT settings

---

src/aap_eda/api/views/activation.py
src/aap_eda/wsapi/consumers.py

This PR depends on https://github.com/ansible/eda-server/pull/634

Replace activation with parent object

---

poetry.lock
pyproject.toml
src/aap_eda/api/vault.py
tests/integration/api/test_vault.py
tools/docker/Dockerfile

https://issues.redhat.com/browse/AAP-19426

feat: Enable to encrypt and decrypt a string by ansible-vault

---

src/aap_eda/core/management/commands/dump_auth_config.py
tests/unit/commands/test_dump_auth_config.py

* add a new management command to dump authenticator config data to json file
* add tests for the new command
Solves: [AAP-19982](https://issues.redhat.com/browse/AAP-19982)

[AAP-19982] Add management command to output authentication settings

---

src/aap_eda/api/serializers/event_stream.py
src/aap_eda/api/serializers/fields/yaml.py
src/aap_eda/api/serializers/rulebook.py
src/aap_eda/api/serializers/utils.py

Move the definition of YAMLSerializerField to a separate field file.

Define YAMLSerializerField in its own file

---

src/aap_eda/services/activation/engine/ports.py
src/aap_eda/services/project/__init__.py
src/aap_eda/services/project/imports.py
src/aap_eda/settings/default.py
src/aap_eda/tasks/project.py
tests/integration/services/activation/engine/test_ports.py
tests/integration/services/data/project-05-import.json
tests/integration/services/data/project-05/extensions/eda/rulebooks/bad1.yml
tests/integration/services/data/project-05/extensions/eda/rulebooks/bad10.yml
tests/integration/services/data/project-05/extensions/eda/rulebooks/bad2.yml
tests/integration/services/data/project-05/extensions/eda/rulebooks/bad3.yml
tests/integration/services/data/project-05/extensions/eda/rulebooks/bad4.yml
tests/integration/services/data/project-05/extensions/eda/rulebooks/bad5.yml
tests/integration/services/data/project-05/extensions/eda/rulebooks/bad6.yml
tests/integration/services/data/project-05/extensions/eda/rulebooks/bad7.yml
tests/integration/services/data/project-05/extensions/eda/rulebooks/bad8.yml
tests/integration/services/data/project-05/extensions/eda/rulebooks/bad9.yml
tests/integration/services/data/project-05/extensions/eda/rulebooks/good.yml
tests/integration/services/test_project_import.py

Merge from main

---

tools/docker/docker-compose-dev.yaml

* Join a common named network that components can discover one another and talk on. Related to https://github.com/ansible/aap-gateway/pull/235

Add eda to the service mesh network

---

src/aap_eda/services/activation/engine/podman.py
tests/integration/services/activation/engine/test_podman.py

https://issues.redhat.com/browse/AAP-20968

fix: remove tracebacks from backend logs when pulling image is timed out

---

src/aap_eda/api/serializers/activation.py
src/aap_eda/api/serializers/event_stream.py
src/aap_eda/api/serializers/utils.py
src/aap_eda/api/vault.py
tests/integration/api/test_activation.py
tests/integration/api/test_event_stream.py

https://issues.redhat.com/browse/AAP-20874
Depends on https://github.com/ansible/ansible-rulebook/pull/651

feat: optionally save encrypted data to extra vars using system_vault_credentials

---

src/aap_eda/services/project/imports.py
tests/integration/services/data/project-05-import.json
tests/integration/services/data/project-05/extensions/eda/rulebooks/good.yml

AAP-21573: Rulebook validation fails on rulebooks with the 'actions' keyword

fix: rulebook validation accepts actions

---

src/aap_eda/services/project/imports.py
tests/integration/services/test_project_import.py

Fix [AAP-21641](https://issues.redhat.com/browse/AAP-21641)

fix: include git_hash in update_fields when save a project

---

src/aap_eda/api/serializers/project.py
src/aap_eda/api/views/project.py
src/aap_eda/core/migrations/0027_credentialtype_alter_permission_resource_type_and_more.py
src/aap_eda/core/models/project.py
tests/integration/api/test_project.py

Include corresponding changes for project view and serializer
AAP-21743: Enhance project model to have more fields for pulling from git

feat: add more optional fields to project model

---

poetry.lock
src/aap_eda/api/serializers/auth.py
src/aap_eda/api/serializers/organization.py
src/aap_eda/api/serializers/team.py
src/aap_eda/core/migrations/0027_organization_team_and_more.py
src/aap_eda/core/migrations/0028_add_default_organization.py
src/aap_eda/core/migrations/_dab_rbac.py

Related PR: https://github.com/ansible/django-ansible-base/pull/209

Remove 'on' from [created|modified]_on

---

.github/workflows/ci.yaml
tests/integration/api/conftest.py
tests/integration/api/test_activation.py
tests/integration/api/test_credential.py
tests/integration/dab_rbac/conftest.py

Getting a start on this, @Dostonbek1

[RBAC] First pass at fixing existing eda-server RBAC tests

---

src/aap_eda/api/serializers/decision_environment.py
src/aap_eda/api/serializers/project.py
src/aap_eda/api/serializers/user.py
src/aap_eda/api/views/decision_environment.py
src/aap_eda/api/views/user.py
tests/integration/api/conftest.py
tests/integration/api/test_activation.py
tests/integration/api/test_activation_instance.py
tests/integration/api/test_auth.py
tests/integration/api/test_credential.py
tests/integration/api/test_decision_environment.py
tests/integration/api/test_event_stream.py
tests/integration/api/test_extra_var.py
tests/integration/api/test_pagination.py
tests/integration/api/test_project.py
tests/integration/api/test_rulebook.py
tests/integration/api/test_user.py
tests/integration/conftest.py
tests/integration/dab_rbac/conftest.py
tests/integration/wsapi/test_consumer.py

This PR aims to refactor existing integration tests as well as updating them to adjust to the new RBAC implementation, although the bulk of the changes are refactors for tests to use fixtures. 
EDIT:
All tests are now passing 🟢

Refactor & fix integration tests on RBAC branch

---

src/aap_eda/core/management/commands/create_initial_data.py
tests/integration/api/test_activation.py
tests/integration/api/test_activation_with_credential.py
tests/integration/api/test_eda_credential.py
tests/integration/conftest.py
tests/integration/wsapi/test_consumer.py

https://issues.redhat.com/browse/AAP-21987
Create a fixture to pre-load supported credentials types.

chore: refactor tests for credential types

---

src/aap_eda/api/views/project.py
tests/integration/api/test_project.py

Some recently added fields to project cannot be updated through the PATCH api. The previous code hard coded fields to be udpated. Now use setattr method to update all fields in the payload.

fix: partial_update project

---

src/aap_eda/api/serializers/eda_credential.py

https://issues.redhat.com/browse/AAP-22188

Allow references is nullable in the output of eda credential

---

src/aap_eda/settings/default.py

Recover a missing commit from https://github.com/ansible/eda-server/pull/632
Jira: https://issues.redhat.com/browse/AAP-20046

chore: support a databases object setting

---

src/aap_eda/api/serializers/activation.py
src/aap_eda/wsapi/consumers.py
src/aap_eda/wsapi/messages.py
tests/integration/api/test_activation_with_credential.py
tests/integration/wsapi/test_consumer.py

https://issues.redhat.com/browse/AAP-22061

feat: enable to send controller information via aap credential type

---

src/aap_eda/core/urls.py
src/aap_eda/core/views.py
tests/integration/core/test_views.py

Please see:  https://issues.redhat.com/browse/AAP-22421 and https://issues.redhat.com/browse/AAPRFE-1202

[AAP-22421] - public ping endpoint for http healthchecks

---

src/aap_eda/core/utils/credentials.py
tests/integration/api/test_eda_credential.py

https://issues.redhat.com/browse/AAP-22572

fix: empty encrypted fields should not be sent to caller

---

src/aap_eda/api/filters/eda_credential.py
tests/integration/api/test_eda_credential.py

https://issues.redhat.com/browse/AAP-22586

chore: Add filter on credential type ids

---

src/aap_eda/api/views/credential_type.py
tests/integration/api/test_credential_type.py

https://issues.redhat.com/browse/AAP-22565

chore: raise conflict error when deleting a credential type with linked credentials

---

src/aap_eda/api/views/eda_credential.py
tests/integration/api/test_eda_credential.py

https://issues.redhat.com/browse/AAP-22026

chore: check related resources when try to delete eda credentials

---

src/aap_eda/api/views/credential_type.py
tests/integration/api/test_credential_type.py

https://issues.redhat.com/browse/AAP-22563
UI will show the following error if credentials exist.

feat: check if has associated credetials before updating the credential type

---

src/aap_eda/api/serializers/activation.py
tests/integration/api/test_k8s_activation.py

https://issues.redhat.com/browse/AAP-21464

fix: add missing service name in retrieving activations

---

src/aap_eda/core/management/commands/create_initial_data.py
tests/integration/core/test_create_initial_data.py

Any converted credentials are deleted. But if they are recreated by any customized script, duplicated credentials should be skipped.
AAP-22365: EDA create_initial_data command is no longer idempotent

fix: skip already converted credentials

---

src/aap_eda/api/serializers/activation.py
src/aap_eda/api/serializers/event_stream.py
src/aap_eda/core/validators.py
tests/unit/test_validators.py

rfc_1035 was incorrectly being used as rcf_1035 in some places Changed it to be rfc_1035

chore: fixed typo

---

src/aap_eda/api/serializers/activation.py
src/aap_eda/api/serializers/credential_type.py
src/aap_eda/api/serializers/decision_environment.py
src/aap_eda/api/serializers/eda_credential.py
src/aap_eda/api/serializers/project.py
src/aap_eda/api/serializers/team.py
src/aap_eda/api/views/project.py
src/aap_eda/core/validators.py
tests/integration/api/test_decision_environment.py
tests/integration/api/test_project.py
tests/integration/dab_rbac/test_related_permissions.py

validations of credential_id, credential_type_id, organization_id were missing in various places.
AAP-23105: Need to validate association ids

fix: validate the existence of association by id for creation or update

---

src/aap_eda/tasks/orchestrator.py

Renamed to get_least_busy_queue_name consistent with description.

chore: rename get_most_free_queue_name

---

src/aap_eda/api/views/project.py
tests/integration/dab_rbac/test_related_permissions.py

Test and fix related obj permission check

---

src/aap_eda/api/serializers/eda_credential.py
src/aap_eda/core/utils/credentials.py
tests/integration/api/test_eda_credential.py

https://issues.redhat.com/browse/AAP-23402

fix: validate credential's inputs when it is empty

---

src/aap_eda/api/serializers/team.py

JIRA: [AAP-23506](https://issues.redhat.com/browse/AAP-23506)

fix: change organization_id to be required for Team Create serializer

---

src/aap_eda/api/serializers/eda_credential.py
tests/integration/api/test_eda_credential.py

https://issues.redhat.com/browse/AAP-23498

fix: credential deletion when it's attached project as GPG type

---

src/aap_eda/core/utils/credentials.py
tests/integration/api/test_eda_credential.py

https://issues.redhat.com/browse/AAP-23402

fix: validate and raise errors if required fields are empty

---

tests/integration/conftest.py
tests/integration/services/activation/test_manager.py
tests/integration/tasks/test_orchestrator.py

https://issues.redhat.com/browse/AAP-23575

fix: remove dependency on EDA_PODMAN_SOCKET_URL

---

src/aap_eda/api/views/organization.py

* update `organizations/<id>/teams/` method to properly check for organization existence and raising exception 
JIRA: [AAP-23508](https://issues.redhat.com/browse/AAP-23508)

fix: update organizations/<id>/teams/ endpoint method

---

src/aap_eda/api/serializers/organization.py
tests/integration/api/test_organization.py
tests/integration/dab_rbac/conftest.py

* add validation for updating organizations to disallow updating default org
JIRA: [AAP-23540](https://issues.redhat.com/browse/AAP-23540)

fix: change default org to be immutable

---

src/aap_eda/api/serializers/activation.py
src/aap_eda/api/serializers/decision_environment.py
src/aap_eda/api/serializers/project.py
src/aap_eda/core/validators.py
tests/integration/api/test_activation_with_credential.py
tests/integration/api/test_decision_environment.py
tests/integration/api/test_project.py

https://issues.redhat.com/browse/AAP-23583

feat: add validation on credentials to make sure their types are valid during creating/updating of activations, projects or decision_environments

---

tools/docker/docker-compose-stage.yaml

similar to what has done to docker-compose-dev in #862

chore: add squid node to stage

---

.github/workflows/e2e-dispatch.yml

Add to the e2e-dispatch workflow the tests for multinode based on docker-compose-dev implemented in https://github.com/ansible/eda-qa/pull/370
Jira: https://issues.redhat.com/browse/AAP-23959

test: add e2e multinode for e2e-dispatch workflow

---

src/aap_eda/core/utils/credentials.py
tests/integration/api/test_eda_credential.py
tests/unit/test_credential_validation.py

https://issues.redhat.com/browse/AAP-24520

Add more output when validating GPG key fails

---

poetry.lock
pyproject.toml

https://github.com/ansible/django-ansible-base/releases/tag/2024.5.23

DAB Update May 23

---

src/aap_eda/core/utils/credentials.py

https://issues.redhat.com/browse/AAP-24520

fix: change GNUPGHOME to point to temp directory to avoid permission issue

---

src/aap_eda/core/tasking/__init__.py

Scheduler and workers automatically wait on the service_id being ready so that we don't rely on  the installer or operator to maintain the start-up dependency.
Do not wait if the startup is for migration
Update:
Based on the discussion, this PR now only raise an error if the process is running as a server, a scheduler, or a worker. It does not wait on possible migration done by another process.

fix: raise an error if service_id is not ready

---

tools/docker/docker-compose-stage.yaml

Made similar changes as in https://github.com/ansible/eda-server/pull/559 for docker-compose-stage.yaml

fix: change ports configurable in docker-compose-stage.yaml

---

src/aap_eda/api/serializers/decision_environment.py
src/aap_eda/core/validators.py
tests/integration/api/test_decision_environment.py

For container registry credential you need
* username and password 
or
* password (token)
If one of the above conditions is not met we will treat it as a Bad Request and not create the Decision Environment
https://issues.redhat.com/browse/AAP-23517

fix: validate registry credential for completeness

---

.github/workflows/e2e-dispatch.yml

To match changes made in the eda-qa repo.

ci: update test path for whitebox tests

---

src/aap_eda/api/filters/user.py
src/aap_eda/api/views/user.py

This is a followup to the PR https://github.com/ansible/eda-server/pull/963 to switch to using `UserFilter` to achieve the same purpose and to keep the code cleaner.

feat: change to using filter class for is_superuser filter

---

tools/docker/Dockerfile

AAP-26860: unable to create local directories (/.ansible/tmp)
replaces #976 
image for test: quay.io/bilwei/eda-server:home2

fix: set HOME in Dockerfile

---

src/aap_eda/api/serializers/__init__.py
src/aap_eda/api/serializers/fields/yaml.py
src/aap_eda/api/serializers/source.py
src/aap_eda/api/views/rulebook.py
src/aap_eda/core/utils/rulebook.py
tests/integration/api/test_rulebook.py
tests/integration/conftest.py
tests/integration/core/test_rulebook.py

https://issues.redhat.com/browse/AAP-28528
Add an endpoint `rulebooks/:id/sources` to display sources defined inside the rulebook.

feat: (AAP-28528) - add endpoint to fetch sources by rulebooks

---

poetry.lock
src/aap_eda/api/views/mixins.py
src/aap_eda/api/views/project.py
src/aap_eda/core/tasking/__init__.py
tests/integration/api/test_project.py

Add redis availability mixin and use of same to disallow project  create/sync when redis is unavailable.
https://issues.redhat.com/browse/AAP-28151

Redis ha/aap 28151

---

src/aap_eda/api/views/activation.py
src/aap_eda/core/models/activation.py
tests/integration/api/test_activation.py

Add redis availability checking to Activation CRUD.
https://issues.redhat.com/browse/AAP-28152

Redis ha/aap 28152

---

src/aap_eda/api/serializers/eda_credential.py
src/aap_eda/api/views/eda_credential.py
tests/integration/api/test_eda_credential.py

https://issues.redhat.com/browse/AAP-29121

feat: (AAP-29121) - Remove force deletion on credentials when event streams use it

---

src/aap_eda/services/activation/activation_manager.py
src/aap_eda/services/activation/engine/common.py
src/aap_eda/services/activation/engine/exceptions.py
src/aap_eda/services/activation/engine/podman.py
tests/integration/services/activation/engine/test_kubernetes.py
tests/integration/services/activation/engine/test_podman.py

https://issues.redhat.com/browse/AAP-29719

fix: (AAP-29719) - enable verify_ssl to skip ssl verify during pulling image from registry

---

.github/workflows/e2e-dispatch.yml
.github/workflows/scheduled.yml

This enables to run e2e tests in upstream mode. 
JIRA: [AAP-30357](https://issues.redhat.com/browse/AAP-30357)

fix(AAP-30357): add a new config variable for e2e tests pipeline

---

src/aap_eda/api/views/project.py
src/aap_eda/core/tasking/__init__.py
tests/integration/api/test_project.py

Undoes any database modifications.

fix: [AAP-30421] catch redis unavailability via exception

---

.github/workflows/e2e-dispatch.yml

Avoid annoying known flaky e2e tests by automatic retries.

ci: update e2e to rerun on failure

---

src/aap_eda/api/serializers/__init__.py
src/aap_eda/api/serializers/mixins.py
src/aap_eda/api/serializers/user.py
src/aap_eda/api/views/user.py
tests/integration/api/test_user.py

JIRA: [AAP-30273](https://issues.redhat.com/browse/AAP-30273)

fix(AAP-30273): allow updating is_superuser field when local resource management is disallowed

---

poetry.lock
src/aap_eda/settings/default.py

AAP-30375: Configure EDA to authenticate prefixed usernames

feat: config AUTHENTICATION_BACKENDS to use PrefixedUserAuthBackend

---

tools/docker/Dockerfile

Depends on https://github.com/ansible/eda-server/pull/1036

Add support for python 3.12 in dockerfile

---

src/aap_eda/api/permissions.py
src/aap_eda/api/views/setting.py

AAP-32353: created superuser by gateway cannot access the system setting API

fix: add IsSystemAdmin permission check

---

src/aap_eda/api/serializers/event_stream.py
tests/integration/api/test_event_stream.py

https://issues.redhat.com/browse/AAP-32874

fix: [AAP-32874] Allow event_stream_type to be none in creating/updating payload

---

.github/workflows/autoupdate-poetry.yml

Adds a missing "if" in the bash script as well as a new conditional to run this workflow only the main repo.

ci: fix autoupdate poetry workflow

---

src/aap_eda/api/serializers/event_stream.py
tests/integration/api/test_event_stream.py

https://issues.redhat.com/browse/AAP-33158

fix: remove event_stream_type from the payload when creating/updating event streams

---

src/aap_eda/api/views/external_event_stream.py
tests/integration/api/test_event_stream_basic.py

fix: check for parsing errors
https://issues.redhat.com/browse/AAP-31364
Catch parsing errors when handling incoming data

fix: AAP-31364 catch parsing errors

---

src/aap_eda/api/serializers/activation.py
tests/integration/api/test_activation.py

https://issues.redhat.com/browse/AAP-33968

fix: change the default value of ruleset_stats of activation to empty string

---

src/aap_eda/core/models/organization.py

EDA doesn't need and doesn't want an assumption of a particular organization by name.

fix: replace OrganizationManager with Manager

---

src/aap_eda/api/serializers/eda_credential.py
tests/integration/api/test_eda_credential.py

https://issues.redhat.com/browse/AAP-34452

fix: add event_streams into credentials refs list

---

src/aap_eda/analytics/analytics_collectors.py
tests/integration/analytics/test_analytics_collectors.py

https://issues.redhat.com/browse/AAP-34684

fix: remove unnecessary data columns from analytics collections

---

poetry.lock
pyproject.toml
src/aap_eda/core/validators.py
tests/integration/api/test_decision_environment.py

https://issues.redhat.com/browse/AAP-30564

fix: check that DE image url is well-formed

---

poetry.lock
pyproject.toml

Follow up analytics revert: https://github.com/ansible/eda-server/pull/1110
Forgot to revert the `distro` package.

chore: remove unused 'distro' dependency

---

src/aap_eda/core/utils/credentials.py
tests/integration/api/test_activation_with_credential.py
tests/integration/api/test_eda_credential.py

This is continuation of work done for JIRA
https://issues.redhat.com/browse/AAP-35882
in PR https://github.com/ansible/eda-server/pull/1139

fix: empty inputs and injectors corner cases

---

src/aap_eda/analytics/analytics_collectors.py
tests/integration/analytics/test_analytics_collectors.py

https://issues.redhat.com/browse/AAP-36177
Collect those event streams that are currently used by activations

feat: collect event streams used by running activations

---

src/aap_eda/api/serializers/activation.py
src/aap_eda/api/serializers/credential_type.py
src/aap_eda/api/views/credential_type.py
src/aap_eda/api/views/eda_credential.py
src/aap_eda/core/enums.py
src/aap_eda/core/exceptions.py
src/aap_eda/core/utils/credentials.py
src/aap_eda/core/utils/strings.py
src/aap_eda/core/validators.py
src/aap_eda/wsapi/consumers.py
src/aap_eda/wsapi/messages.py
tests/integration/api/test_activation.py
tests/integration/api/test_activation_with_credential.py
tests/integration/api/test_credential_type.py
tests/integration/api/test_eda_credential.py
tests/integration/conftest.py
tests/integration/wsapi/test_consumer.py
tests/unit/test_credential_validation.py
tests/unit/test_utils.py

Brings in the relevant updates from our bugfix/injectors branch into our main to better achieve parity with the platform.

AAP-20372 - Merge Bugfix/injectors `Feature` branch into main

---

src/aap_eda/services/activation/activation_manager.py
src/aap_eda/services/activation/engine/podman.py
tests/integration/services/activation/engine/test_podman.py
tests/integration/services/activation/test_manager.py

Investigating other issues I have seen in the log a stack trace like this one:
```
Dec 18 15:09:04 ip-10-0-14-243 automation-eda-controller-activation-worker-3[149381]:  File "/usr/lib/python3.11/site-packages/aap_eda/services/activation/activation_manager.py", line 888, in monitor
Dec 18 15:09:04 ip-10-0-14-243 automation-eda-controller-activation-worker-3[149381]:    container_status = self.container_engine.get_status(
Dec 18 15:09:04 ip-10-0-14-243 automation-eda-controller-activation-worker-3[149381]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 18 15:09:04 ip-10-0-14-243 automation-eda-controller-activation-worker-3[149381]:  File "/usr/lib/python3.11/site-packages/aap_eda/services/activation/engine/podman.py", line 181, in get_status
Dec 18 15:09:04 ip-10-0-14-243 …
```

fix: handle 500 podman response when getting status

---

.pre-commit-config.yaml
pyproject.toml
tools/docker/Dockerfile

Added missing constraints for poetry version, following up https://github.com/ansible/eda-server/pull/1181

chore: ensure correct poetry version

---

src/aap_eda/core/models/base.py
tests/integration/api/test_event_stream_basic.py
tests/integration/conftest.py

https://issues.redhat.com/browse/AAP-38546

fix: [AAP-38546] - Skip anonymous user in updating created_by/modified_by fields

---

src/aap_eda/api/serializers/activation.py
tests/integration/api/test_activation_with_event_stream.py

Perform source swapping at activation editing when event source mapping is provided, no matter a new rulebook is selected or not. Clear existing event stream maaping if a new rulebook is selected but no event source mapping is provided.
AAP-37298: Reattach event streams when rulebook has changed

feat: reattach event streams when rulebook changes

---

src/aap_eda/api/serializers/__init__.py
src/aap_eda/api/serializers/activation.py
src/aap_eda/api/views/activation.py
src/aap_eda/core/validators.py
tests/integration/api/test_activation.py
tests/integration/api/test_activation_with_event_stream.py

feat: new API to copy an activation

---

src/aap_eda/api/serializers/activation.py
tests/integration/api/test_activation_with_event_stream.py

AAP-38379. 
insert pg notify credential when update an activation similar to crate an activation.

fix: tests on activation after merge conflicts

---

src/aap_eda/analytics/analytics_collectors.py
tests/integration/analytics/test_analytics_collectors.py

https://issues.redhat.com/browse/AAP-39892
This PR covers:
1. remove `payload` from audit event collection table,
2. reduce SQL parameter injection and memory overflow risks

[AAP-39892] Optimize analytics collection to create tar files

---

src/aap_eda/analytics/collector.py
src/aap_eda/core/management/commands/gather_analytics.py
src/aap_eda/settings/default.py
tests/integration/analytics/test_collector.py
tests/integration/analytics/test_gather_analytics.py
tests/integration/api/test_feature_flags.py

Renames feature flag to be inline with naming convention FEATURE_(FEATURE_NAME)_ENABLED

EDA_ANALYTICS: Rename feature-flag

---

scripts/create_superuser.sh

- add a `poetry` command check
- add the `usage` for the invalid flag, even invalid flag should show the usage, make a better `UX`.
Closes #XXX (if applicable)
Jira: [AAP-XXXXX](https://jira.aap.com/browse/AAP-XXXXX) (if applicable)
1.
2.
3.

chore: enhance create superuser script

---

docs/contributing.md

- What is being changed?
- Why is this change needed?
- How does this change address the issue?
Closes #XXX (if applicable)
Jira: [AAP-XXXXX](https://jira.aap.com/browse/AAP-XXXXX) (if applicable)
The old link caused `404`, so update it.
1.
2.
3.

docs: update hyperlink

---

.github/pull_request_template.md

As per our discussion, remove the existing template. Replace it with a simpler version that calls for a description.

ci: update pr template

---

Taskfile.dist.yaml

- remove `cmd:` is not necessary
- correct the wrong `ruff` desc
Closes #XXX (if applicable)
Jira: [AAP-XXXXX](https://jira.aap.com/browse/AAP-XXXXX) (if applicable)
1.
2.
3.

chore: update taskfile

---

src/aap_eda/analytics/analytics_collectors.py
tests/integration/analytics/test_analytics_collectors.py

This PR contains:
1. change `activations_stats.csv` into `activations_stats_table.csv`
2. remove `created_by_id` and `modified_by_id` from `teams_table.csv`
https://issues.redhat.com/browse/AAP-41167

[AAP-41167] minor changes for collection tables

---

.gitignore
docs/task_dispatcher.md
poetry.lock
pyproject.toml
src/aap_eda/core/apps.py
src/aap_eda/core/management/commands/run_activation_dispatcher.py
src/aap_eda/core/management/commands/run_worker_dispatcher.py
src/aap_eda/core/tasking/__init__.py
src/aap_eda/services/activation/engine/podman.py
src/aap_eda/services/activation/restart_helper.py
src/aap_eda/settings/default.py
src/aap_eda/tasks/orchestrator.py
src/aap_eda/tasks/project.py
src/aap_eda/utils/db.py
tools/docker/docker-compose-dev.yaml

wip: rename dispatcher to dispatcherd

---

src/aap_eda/services/activation/engine/podman.py

fix: update podman engine log message at stopping container

---

src/aap_eda/services/activation/engine/kubernetes.py
tests/integration/services/activation/engine/test_kubernetes.py

[AAP-41447](https://issues.redhat.com/browse/AAP-41447)
The current Kubernetes 'cleanup' method has a weakness in that it finishes before ensuring that the pod at hand - and also its container resources - are stopped and deleted. Because the delete methods that _cleanup()_ employs run asynchronously, the method may (and has) returned whilst the pod is still running. Herein lies the race condition described in the ticket, where unexpected behavior can occur. 
The solution is to create a _wait_for_pod_deletion(pod_id) method that uses the Kubernetes Watch to observe the stream of events from the kubernetes API, filtered on the pod at hand, that waits until the event type has the value of 'DELETED'. After this method has successfully completed, the cleanup is safe to continue and return.

add wait for pod deletion method

---

src/aap_eda/analytics/utils.py
src/aap_eda/settings/defaults.py
tests/integration/analytics/test_utils.py
tools/docker/docker-compose-dev.yaml
tools/docker/docker-compose-mac.yml
tools/docker/docker-compose-stage.yaml

https://issues.redhat.com/browse/AAP-44131
Rename OIDC_TOKEN_URL to AUTOMATION_ANALYTICS_OIDC_TOKEN_URL

fix: [AAP-44131] rename OIDC_TOKEN_URL more specific

---

src/aap_eda/core/management/commands/rqworker.py
src/aap_eda/core/tasking/hazmat.py
src/aap_eda/settings/post_load.py

wip: fix initial conf

---

poetry.lock
src/aap_eda/core/tasking/__init__.py
src/aap_eda/services/activation/activation_manager.py
src/aap_eda/services/activation/engine/podman.py
src/aap_eda/services/activation/restart_helper.py
src/aap_eda/settings/core.py
src/aap_eda/tasks/analytics.py
src/aap_eda/tasks/orchestrator.py
src/aap_eda/wsapi/consumers.py

wip: upd poetry, add dispatcher to analitics and orchestrator

---

src/aap_eda/api/views/activation.py
src/aap_eda/api/views/project.py
src/aap_eda/core/apps.py
src/aap_eda/core/management/commands/rqworker.py
src/aap_eda/core/tasking/__init__.py
src/aap_eda/services/activation/engine/podman.py
src/aap_eda/services/activation/restart_helper.py
src/aap_eda/tasks/analytics.py
src/aap_eda/tasks/orchestrator.py
src/aap_eda/tasks/project.py

wip: initial implemention finished, pending of real tests

---

poetry.lock
pyproject.toml
src/aap_eda/api/views/project.py
src/aap_eda/tasks/project.py

wip: project import fixed, pending project sync. DAB upgraded

---

src/aap_eda/api/views/project.py
src/aap_eda/core/tasking/__init__.py
src/aap_eda/tasks/orchestrator.py
src/aap_eda/tasks/project.py

wip: projects and monitor working, investigating _manage schedule issues

---

poetry.lock
pyproject.toml
src/aap_eda/api/views/project.py
src/aap_eda/core/tasking/__init__.py
src/aap_eda/services/project/imports.py
src/aap_eda/settings/post_load.py
src/aap_eda/tasks/analytics.py
src/aap_eda/tasks/orchestrator.py
src/aap_eda/tasks/project.py

wip: upgrade dispatcher, projects and activations working. 

---

tests/integration/test_advisory_lock.py

ci: fix isort

---

tests/integration/services/activation/test_manager.py

test: fix test_manager tests

---

src/aap_eda/settings/post_load.py

Follow up https://github.com/ansible/eda-server/pull/1312, add missing ref in conf

chore: followup hazmat renaming, missing ref

---

src/aap_eda/core/management/commands/rqworker.py
tests/unit/commands/test_rq_cmd_wrapper.py

fix command wrapper tests

---

src/aap_eda/core/apps.py

chore: add missing copyright header to apps.py file

---

src/aap_eda/tasks/analytics.py

Address https://github.com/ansible/eda-server/pull/1308#discussion_r2098909146

remove unnecesary decorator for rq analytics

---

poetry.lock
pyproject.toml

https://github.com/ansible/django-ansible-base/releases/tag/2025.7.1
I want to see if anything breaks. And if not, best to go ahead and get it in anyway.

Update DAB to July 1 version

---

src/aap_eda/wsapi/consumers.py

We missed this file when working on
PR https://github.com/ansible/eda-server/pull/1361
https://issues.redhat.com/browse/AAP-51904
We are adding an ATF test to do the real integration test
https://issues.redhat.com/browse/AAP-51905

fix: allow for RHAPP, file content and env vars from SMS
